- README.md
- docs/_includes/bootstrap/components.html
- docs/_layouts/page.html
- docs/derek/bootstrap.md
- docs/derek/components/navigation.html
- docs/derek/index.md
- themes/derek/scss/_main.scss
- themes/derek/scss/components/navigation.scss
Example of how to write demo web pages. Still much to be desired but it is a start.
> feat(layout): add page layout for themes

- _config.yml
- docs/_layouts/default.html
- docs/_layouts/page.html
- docs/derek/examples.html
- docs/getting-started.md
- docs/global/bootstrap.md
- docs/global/components/navigation.html
- docs/global/examples.html
- docs/global/index.md
- docs/index.html
Reverts rackerlabs/zoolander#5
> Revert "chore(docs): update docs with more placeholder content"

- README.md
- package.json
> feat(build): Added build script in npm

- grunt/build.js
- themes/global/js/src/entry.js
This fixes `grunt watch` and updates code style as suggested by @SyntaxStacks
> fix(tests): update code styles and fix watch task

- .mversionrc
- README.md
- package.json
- themes/global/scss/_main.scss
https://jira.rax.io/browse/RSWEB-4695
> feat(bump): mversion for bumping

- styleguide/_layouts/default.jade
- styleguide/derek/examples/_data.json
- styleguide/derek/examples/_landing-page.html
- styleguide/derek/examples/_solutions.html
- styleguide/derek/examples/index.jade
- styleguide/derek/examples/solutions.jade
- styleguide/themes/derek/js/src/entry.js
- styleguide/themes/derek/scss/_main.scss
- styleguide/themes/derek/scss/_modifiers.scss
- styleguide/themes/derek/scss/_variables.scss
- styleguide/themes/derek/scss/components/_solutions.scss
- webpack.config.js
This PR is meant as a kickstart to bringing over our solution page patterns into Zoolander.
> feat(solutions): kickstart solutions pattern example

- styleguide/_sass/_rsweb-font-style.scss
- styleguide/css/main.css
- styleguide/themes/derek/scss/components/rsweb-font-style.scss
A few quick updates to host font icon on cdn.  Currently something wrong with the CDN links so DO NOT MERGE.
EDIT: Fixed, thanks @bighappyface !
> RSWEB-5187 - Move fonticon hosting to cdn. [Needs Review]

- styleguide/themes/derek/scss/components/rsweb-font-style.scss
style(font): RSWEB-5187 - Add in fonticon.
fix(fonticon): RSWEB-5187 - Fix container location.
> RSWEB-5187 - Move fonticon hosting to cdn.

- styleguide/_themes/derek/scss/_modifiers.scss
- styleguide/derek/examples/_solutions.html
This PR adds 3 new background variation: light gray, dark gray, and crumpled paper.
> RSWEB-6029 River Variations

- styleguide/_themes/derek/scss/_modifiers.scss
- styleguide/_themes/global/scss/_modifiers.scss
- styleguide/_themes/global/scss/_modules.scss
- styleguide/css/main.scss
- styleguide/derek/examples/_data.json
- styleguide/derek/examples/_office365.html
- styleguide/derek/examples/_solutions.html
- styleguide/derek/examples/index.jade
- styleguide/derek/examples/office365.jade
https://jira.rax.io/browse/RSWEB-5487
rocket content type, split quote, random small things
(did some things im not proud of in order to prevent snowflake styling)
> feat(zoolander):rsweb-5487

- styleguide/_layouts/default.jade
- styleguide/_themes/global/scss/_modifiers.scss
- styleguide/_themes/global/scss/_modules.scss
- styleguide/derek/examples/_office365.html
- styleguide/js/zoolander.js
https://jira.rax.io/browse/RSWEB-5480
For visibility of the tabs/accordion transition.
> feat(zoolander):rsweb-5480

- styleguide/derek/examples/_solutions.html
This PR gets `_solutions.html` validated and formatted.
> refactor(solutions): clean up html

- styleguide/_themes/global/scss/_buttons.scss
- styleguide/_themes/global/scss/_fonts.scss
- styleguide/_themes/global/scss/_modifiers.scss
- styleguide/_themes/global/scss/_modules.scss
- styleguide/css/global.css
- styleguide/css/main.scss
- styleguide/derek/examples/_office365.html
- styleguide/js/zoolander.js
> feat(zoolander):tabs/pricing tables

- styleguide/_themes/global/scss/_buttons.scss
- styleguide/_themes/global/scss/_modules.scss
- styleguide/derek/examples/_solutions.html
Replaced button tags with anchor tags and reduced the size of the cta when in sub nav.
> style(cta-markup): polishing up new button styles

- styleguide/_themes/global/scss/_modules.scss
- styleguide/derek/examples/_solutions.html
Creating variations of business resources
https://jira.rax.io/browse/RSWEB-6073
> feat(zoolander):business-resources

- styleguide/_themes/global/scss/_modules.scss
- styleguide/css/global.css
https://jira.rax.io/browse/RSWEB-5457
Fixing font-awesome issue for back to top rug.
> bug(zoolander):font-awesome-rug-fix

- styleguide/_themes/derek/scss/_modifiers.scss
- styleguide/derek/examples/_office365.html
https://jira.rax.io/browse/RSWEB-6052
> RSWEB-6052: enterprise managed services

- styleguide/derek/examples/_office365.html
https://jira.rax.io/browse/RSWEB-6051
> RSWEB-6051: enterprise features

- styleguide/derek/examples/_office365.html
https://jira.rax.io/browse/RSWEB-6050
> RSWEB-6050: additional resources

- styleguide/_themes/global/scss/_modifiers.scss
- styleguide/derek/examples/_office365.html
https://jira.rax.io/browse/RSWEB-6049
> RSWEB-6049: overview features

- styleguide/_themes/global/scss/_buttons.scss
- styleguide/_themes/global/scss/_fonts.scss
- styleguide/_themes/global/scss/_modules.scss
- styleguide/derek/examples/_office365.html
https://jira.rax.io/browse/RSWEB-5478
Wrapped in business tabs. Closing that PR.
> feat(zoolander):enterprise button up

- styleguide/derek/examples/_solutions.html
Easier to review when removing whitespace - follow this link! https://github.com/rackerlabs/zoolander/pull/59/files?w=1
> Updates infrastructure and services grid example.

- styleguide/_themes/global/scss/_banners.scss
- styleguide/_themes/global/scss/_buttons.scss
- styleguide/derek/examples/_office365.html
This PR adds the corrects the CTA styles when applied to banner.
> style(banner-cta): fix banner cta style

- styleguide/_themes/global/scss/_fonts.scss
- styleguide/_themes/global/scss/_modules.scss
- styleguide/css/global.css
- styleguide/css/main.css
- styleguide/css/main.scss
- styleguide/derek/examples/_homepage.html
- styleguide/derek/examples/_solutions.html
Fixes for subnav/icon color and homepage additions.
> feat(zoolander):homepage/subnav/mobile

- styleguide/_themes/global/scss/_modules.scss
@SyntaxStacks code review and merge?
> various fixes for tabs and subnav

- styleguide/_themes/global/scss/_buttons.scss
Prevents text on hover for learning cta
> style(leaning-cta-hover): white font on hover

- styleguide/_themes/global/scss/_fonts.scss
- styleguide/_themes/global/scss/_modules.scss
teal checks, icon resizing, mobile view of compare charts.
> fixing mobile version of compare tabs

- styleguide/_themes/global/scss/_modules.scss
- styleguide/derek/examples/_office365.html
Compare table code and panel-heading fix.
> mass compare table

- styleguide/_themes/derek/scss/_modifiers.scss
- styleguide/_themes/global/scss/_fonts.scss
- styleguide/_themes/global/scss/_modules.scss
- styleguide/derek/examples/_solutions.html
Creating the features pattern. Let me know if I need to change the padding classes to be more consistent with what we went with for the river and what not. That stuff is more for placement only.
> features pattern creation

- styleguide/_themes/global/scss/_modifiers.scss
- styleguide/derek/examples/_solutions.html
> style(modifiers): remove important from .no-padding

- styleguide/_themes/global/scss/_modules.scss
- styleguide/derek/examples/_solutions.html
This PR sets the `.rsweb` icon colors for the key offer and product feature patterns.
> style(patterns): set icon color for key offers and features

- styleguide/_themes/global/scss/_fonts.scss
@bighappyface here is the fix for the ul alignment on www. There is another portion for the footer in the www repo.
> fixing ul alignment in www

- styleguide/_themes/global/scss/_fonts.scss
- styleguide/_themes/global/scss/_modules.scss
- styleguide/derek/examples/_solutions.html
This PR pulls the "read more" text out of the IaS grid pattern pivots to using defined modifier classes.
> style(grid): adjust read-more and ias spacing

- styleguide/derek/examples/_solutions.html
Fixed key offers. Sorry guys! Equal height will totally work now.
> a fix for the key offers to have equal height

- styleguide/_themes/global/scss/_modules.scss
- styleguide/derek/_partials/grid/widget/additional-resource.ejs
- styleguide/derek/_partials/grid/widget/business-resource.ejs
- styleguide/derek/_partials/grid/widget/ias.ejs
- styleguide/derek/_partials/grid/widget/key-offer.ejs
- styleguide/derek/_partials/grid/widget/list.ejs
- styleguide/derek/_partials/grid/widget/product-feature.ejs
- styleguide/derek/_partials/grid/widget/value-prop.ejs
- styleguide/derek/examples/solutions.ejs
This PR pulls out grid patterns into partials to centralize markup and setup the patterns for expanded consistency.
> feat(derek): convert grid patterns to partials

- styleguide/_themes/global/scss/_modifiers.scss
- styleguide/_themes/global/scss/_modules.scss
- styleguide/derek/_partials/grid/widget/additional-resource.ejs
- styleguide/derek/_partials/grid/widget/ias.ejs
- styleguide/derek/_partials/grid/widget/key-offer.ejs
- styleguide/derek/examples/solutions.ejs
switching up code for resources. adding in and hopefully cleaning up …
> switching up code for resources. adding in and cleaning up

- styleguide/_themes/derek/scss/components/_tabs.scss
- styleguide/_themes/derek/scss/snowflakes/_o365.scss
Styling changes needed for o365 mobile price additions.
https://jira.rax.io/browse/RSWEB-6169
> Price addition styling needed for o365 tables

- styleguide/_themes/derek/scss/components/_tabs.scss
- styleguide/derek/_partials/solutions/tabs.ejs
Removed the h2, p stylings to any element nested in the tab anchor would be styled
> fix(tabs): Fixed style for tabs

- styleguide/_themes/derek/scss/components/_tabs.scss
removed h2, p styles in favor of first element
> fix(tabs): Tab style updates

- styleguide/_themes/derek/scss/components/_ceiling.scss
- styleguide/derek/_partials/_ceiling.ejs
- styleguide/derek/_partials/_rug.ejs
- styleguide/derek/examples/landing-page.ejs
Creating the bootstrapped ceiling.
> Global elements - ceiling

- styleguide/derek/_partials/solutions/tabs.ejs
Changed bg color and added a container to the interior of the tabs per EJ's request to fix issues on cloud pricing pages.
> Adjusting tabs structure per rsweb-6236

- styleguide/_themes/derek/scss/components/_navigation.scss
- styleguide/_themes/global/scss/_buttons.scss
- styleguide/derek/_partials/solutions/subnav.ejs
https://jira.rax.io/browse/RSWEB-6180
Removes states which cause subnav cta to appear colors other than signup green.
> RSWEB-6180: remove subnav cta visited focus active states

- styleguide/_themes/derek/scss/components/_footer.scss
- styleguide/_themes/global/scss/_modifiers.scss
- styleguide/derek/_partials/_footer.ejs
- styleguide/js/zoolander.js
https://jira.rax.io/browse/RSWEB-6228
> RSWEB-6228: Bootstrapped footer

- styleguide/_themes/derek/scss/components/_ceiling.scss
- styleguide/_themes/derek/scss/components/_footer.scss
- styleguide/_themes/derek/scss/components/_navigation.scss
- styleguide/_themes/derek/scss/components/_rug.scss
- styleguide/_themes/global/scss/_fonts.scss
- styleguide/_themes/global/scss/_forms.scss
- styleguide/_themes/global/scss/_swatch.scss
- styleguide/derek/_partials/_footer.ejs
- styleguide/derek/_partials/_rug.ejs
- styleguide/derek/_partials/grid/widget/list.ejs
- styleguide/derek/_partials/grid/widget/product-feature.ejs
- styleguide/derek/_partials/grid/widget/value-prop.ejs
- styleguide/derek/_partials/solutions/value-prop.ejs
https://jira.rax.io/browse/RSWEB-6385
- Underlines all links in content and removes the requirement of surrounding `<p>` tags. 
- Updates navigation and footer elements to maintain current styles.
> RSWEB-6385: default links to be underlined in content

- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/derek/scss/components/_basement.scss
- styleguide/_themes/derek/scss/components/_regionSelector.scss
- styleguide/derek/_partials/_basement.ejs
- styleguide/derek/_partials/_regionSelector.ejs
- styleguide/derek/examples/_layout.jade
Jira: https://jira.rax.io/browse/RSWEB-6332
This PR was an add-on to the original task to refactor the region selector using bootstrap.
> RSWEB-6332 [zoolander] Rebuild Region Selector

- styleguide/_themes/derek/scss/components/_basement.scss
This PR fixes a side-scrolling issue introduced by a previous commit.
> fix(basement): Fix side-scrolling issue and copyright text alignment.

- styleguide/_themes/derek/scss/components/_footer.scss
This PR fixes a one-off issue when viewing the site on an iPad.
> chore(footer): Fix iPad footer issue

- styleguide/_themes/derek/scss/patterns/grid/_modules.scss
- styleguide/_themes/global/scss/_modifiers.scss
- styleguide/_themes/global/scss/_swatch.scss
Adding in the cornerPocket styling to zoolander. Also removing some unused swatches.
> cornerPocket styling

- .gitignore
- .sass-lint.yml
- .travis.yml
- backstop_data/bitmaps_test/compare.json
- hooks
- package.json
> feat(lint): Added sass linter

- .sass-lint.yml
- package.json
https://jira.rax.io/browse/RSWEB-6638
> chore(lint): rsweb-6638 Sass Lint Class names

- styleguide/_layouts/default.jade
- styleguide/_themes/derek/scss/_modifiers.scss
- styleguide/_themes/global/scss/_bootstrap_variables.scss
- styleguide/_themes/global/scss/_fonts.scss
- styleguide/derek/examples/_data.json
- styleguide/derek/examples/font-usage.ejs
- styleguide/derek/examples/index.jade
https://jira.rax.io/browse/RSWEB-6251
> adding font usage example page with multilingual previews

- styleguide/_themes/derek/scss/components/_basement.scss
> RSWEB-6655: basement sass fixes

- styleguide/_themes/derek/scss/components/_back-to-top.scss
> RSWEB-6655: back to top sass fixes

- styleguide/_themes/derek/scss/components/_banners.scss
> RSWEB-6655: banners sass fixes

- styleguide/_themes/derek/scss/components/_regionSelector.scss
This clears sass errors and adds a flag-icon mixin to handle the multiple similar region classes.
> RSWEB-6655: region selector sass fixes

- styleguide/_themes/derek/scss/_main.scss
> RSWEB-6655: derek main sass fixes

- styleguide/_themes/derek/scss/components/_tabs.scss
> RSWEB-6655: tabs sass fixes

- styleguide/_themes/global/scss/_buttons.scss
> RSWEB-6655: global buttons sass fixes

- styleguide/_themes/derek/scss/patterns/grid/_modules.scss
> RSWEB-6655: derek modules sass fixes

- styleguide/_themes/global/scss/_forms.scss
> RSWEB-6655: global forms sass fixes

- styleguide/_themes/derek/scss/patterns/grid/_resources.scss
> RSWEB-6655: resources sass fixes

- styleguide/_themes/derek/scss/snowflakes/_o365.scss
Fixes the majority of lint errors without changing styles.
4 errors remain. 
2 - ID selectors being used
1 - nesting greater than 3 
1 - class should match regular expression
> RSWEB-6655: o365 sass fixes

- styleguide/css/main.scss
Some colors are in hex format. Errors demanding that they be variables remain.
> RSWEB-6655: css main.scss sass fixes

- styleguide/_themes/global/scss/global.scss
Leading underscore errors persist regarding the names of the imported files.
> RSWEB-6655: global-scss-global sass fixes

- .sass-lint.yml
- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/derek/scss/components/_ceiling.scss
- styleguide/_themes/derek/scss/components/_ceilingLp.scss
- styleguide/_themes/global/scss/_bootstrap_overrides.scss
- styleguide/_themes/global/scss/global.scss
- styleguide/derek/_partials/_ceiling.ejs
- styleguide/derek/_partials/_ceilingLp.ejs
- styleguide/derek/examples/_layout.jade
- styleguide/derek/examples/forms.ejs
- styleguide/derek/examples/homepage.ejs
- styleguide/derek/examples/landing-page.ejs
- styleguide/derek/examples/office365.ejs
- styleguide/derek/examples/solutions.ejs
Jira: https://jira.rax.io/browse/RSWEB-6673
This PR converts the ceiling into maintainable CSS.
> RSWEB-6673 Convert zoolander ceiling to use maintainable CSS.

- .sass-lint.yml
- styleguide/_themes/global/scss/_fonts.scss
> RSWEB-6655: global fonts sass fixes

- styleguide/_themes/derek/scss/components/_footer.scss
- styleguide/_themes/global/scss/_bootstrap_overrides.scss
> RSWEB-6655: footer sass fixes

- styleguide/_themes/derek/scss/components/_rug.scss
> RSWEB-6655: rug sass error

- styleguide/_themes/derek/scss/patterns/_quote.scss
> RSWEB-6655: fix quote sass errors

- styleguide/_themes/derek/scss/patterns/grid/_businessResource.scss
> RSWEB-6655: fix br sass errors

- styleguide/_themes/global/scss/_modifiers.scss
> RSWEB-6655: global modifiers sass fixes

- styleguide/_themes/derek/scss/_modifiers.scss
- styleguide/_themes/derek/scss/patterns/grid/_productFeatures.scss
There are remaining warnings related to Vendor prefixes and nesting classes 3 levels.
> RSWEB-6655: derek modifiers and product features sass fixes

- styleguide/_themes/global/scss/_swatch.scss
> RSWEB-6655: swatch sass error fix

- styleguide/_themes/derek/scss/derek.scss
> RSWEB-6655: derek.scss sass-lint errors fixed

- styleguide/_themes/derek/scss/components/_navigation.scss
- styleguide/_themes/global/scss/_bootstrap_overrides.scss
> RSWEB-6655: nav sass error fixes

- styleguide/_themes/derek/scss/patterns/grid/_keyOffers.scss
> RSWEB-6655: _keyOffers sass-lint errors fixed

- package.json
- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/derek/scss/components/_ceiling.scss
- styleguide/_themes/derek/scss/patterns/_quote.scss
- styleguide/_themes/derek/scss/patterns/grid/_resources.scss
- styleguide/_themes/global/scss/_fonts.scss
- styleguide/_themes/global/scss/global.scss
- styleguide/css/derek.scss
- styleguide/css/global.scss
> RSWEB-6655: sass errors

- styleguide/css/main.scss
This PR is a quick fix for bug introduced by #163.
> RSWEB-6329: Fixes harp:compile bug

- styleguide/_themes/derek/scss/components/mainnav.scss
Couple issues introduced by mixing spans and anchor tags and bootstraps subsequent freakout.
> making minor adjustments to main nav

- styleguide/_themes/derek/scss/components/mainnav.scss
> feat(chat): Chat Hidden Style for mobile

- styleguide/_themes/derek/scss/components/subnav.scss
Jira: https://jira.rax.io/browse/RSWEB-6765
This PR fixes subnav link color (and a few sass lint errors).
> RSWEB-6765: Fix subnav link color

- package.json
- scripts/hooks.sh
- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/derek/scss/components/ticker.scss
- styleguide/derek/_partials/ticker.ejs
- styleguide/derek/examples/landing-page.ejs
https://jira.rax.io/browse/RSWEB-6705
> feat(ticker): rsweb-6705 Openstack Ticker

- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/derek/scss/modifiers.scss
- styleguide/_themes/derek/scss/patterns/announcements.scss
- styleguide/derek/_partials/solutions/announcements.ejs
- styleguide/derek/examples/solutions.ejs
https://jira.rax.io/browse/RSWEB-6475
> pattern(zoolander):added announcement pattern

- styleguide/_themes/derek/scss/components/mainnav.scss
- styleguide/derek/_partials/_mainnav.ejs
@bighappyface This should work for the ask you had for adding support for drop down labels. You can see it on Managed Offerings. Let me know if you need anything else for this one!
> adding support for dropdown labels

- styleguide/_themes/derek/scss/components/ceilingLp.scss
This PR removes the border from the landing page ceiling.
> RSWEB-6327: Remove bottom border from ceiling landing page. 

- styleguide/_themes/derek/scss/components/ceilingLp.scss
This PR fixes logo padding on mobile for the ceiling
> fix(ceiling-padding): Fix logo padding on ceiling on mobile

- styleguide/_themes/derek/scss/patterns/grid/productFeatures.scss
- styleguide/derek/_partials/grid/widget/product-feature.ejs
- styleguide/derek/_partials/solutions/features.ejs
https://jira.rax.io/browse/RSWEB-6176
Adding in product icon padding. Went ahead and updated some naming to be more maintainable friendly. Didn't do a full refactor but its closer to the goal.
Will need an adjustment to the pattern in www for class names. If everyone is good with that then I'll go ahead and open a www PR.
> bug(styleguide):add padding to features icon

- package.json
- styleguide/_themes/global/scss/forms.scss
- styleguide/_themes/global/scss/global.scss
- styleguide/_themes/global/scss/tables.scss
- styleguide/derek/examples/_layout.jade
- styleguide/derek/examples/tables.ejs
https://jira.rax.io/browse/RSWEB-6675
Added some table styling and put in some examples for that. Didn't add to the examples page because of the front end changes going through review anyways. Don't want to add it twice.
@bighappyface, @WidgetsBurritos I'm curious about if you're okay with my treatment on horizontal-scroll. Im pretty sure in maintainable they would say each element should have an additional class put on it to handle horizontal scrolling changes but I would really want to avoid doing that. Especially since tables wont be a pattern and will be utilized by ECMs on occasion.
That's a group decision though.
I also took the opportunity to switch up the hex values in forms.scss to get us down to 120 sass-lint errors.
> table-styling

- styleguide/_themes/derek/scss/components/subnav.scss
https://jira.rax.io/browse/RSWEB-6762
> fix(subnav): rsweb-6762 subnav fix

- .sass-lint.yml
- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/derek/scss/modifiers.scss
- styleguide/_themes/derek/scss/patterns/grid/ias.scss
- styleguide/_themes/global/scss/global.scss
- styleguide/_themes/global/scss/modifiers.scss
- styleguide/_themes/global/scss/vendor_prefixes.scss
- styleguide/derek/_partials/_mainnav.ejs
- styleguide/derek/_partials/grid/widget/ias-no-hover.ejs
- styleguide/derek/_partials/grid/widget/ias.ejs
- styleguide/derek/_partials/solutions/services-3-col.ejs
- styleguide/derek/_partials/solutions/services-4-col.ejs
- styleguide/derek/_partials/solutions/services-5-col.ejs
- styleguide/derek/_partials/solutions/services-6-col.ejs
https://jira.rax.io/browse/RSWEB-6703
> RSWEB-6703: ias hover refactor

- package.json
- styleguide/_themes/derek/scss/components/ceiling.scss
- styleguide/_themes/derek/scss/components/ceilingLp.scss
- styleguide/_themes/derek/scss/components/footer.scss
- styleguide/_themes/derek/scss/components/mainnav.scss
- styleguide/_themes/derek/scss/components/rug.scss
- styleguide/derek/_partials/_footer.ejs
- styleguide/derek/_partials/_mainnav.ejs
> adjustments for main nav

- styleguide/_layouts/default.jade
- styleguide/_themes/derek/scss/components/mainnav.scss
- styleguide/derek/_partials/_mainnav.ejs
- styleguide/js/zoolander.js
This PR fixes android nav problems.
> RSWEB-6327: Fix Android jankiness

- styleguide/_themes/derek/scss/patterns/blog-feed.scss
This PR fixes a bug introduced by last merge.
> fix(bug): Fixes color name bug issue.

- styleguide/_themes/derek/scss/components/ticker.scss
https://jira.rax.io/browse/RSWEB-6869
Fixing bouncing text and adjusting column width for 1B width. 
While I was in there I adjusted image width for mobile and moved down title per a request from @ejchiefs
> bug(ticker):value-bounce-fix

- styleguide/_themes/global/scss/tables.scss
https://jira.rax.io/browse/RSWEB-6880
updates table feature to break text
> RSWEB-6880: set width for feature

- styleguide/_themes/derek/scss/components/ticker.scss
> doubling letter spacing on ticker to prevent jitter

- styleguide/_themes/derek/scss/components/ticker.scss
https://jira.rax.io/browse/RSWEB-6926
> zoolander(bugfix): adjusted ticker string so that it won't jitter around

- styleguide/derek/examples/index.jade
This gets rid of an old merge artifact.
> fix(jade): remove leftover conflict articfact

- .travis.yml
- package.json
- styleguide/_themes/derek/scss/components/ticker.scss
https://jira.rax.io/browse/RSWEB-6833
Fix to complete that work
> chore(ticker): rsweb-6833 Ticker Grid Fix

- package.json
- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/derek/scss/patterns/lead.scss
- styleguide/_themes/derek/scss/snowflakes/homepage.scss
- styleguide/_themes/derek/scss/snowflakes/swatches.scss
This PR fixes lead issues and a sass bug.
> Fix lead and sass bugs

- .sass-lint.yml
- styleguide/_layouts/default.jade
- styleguide/_themes/derek/scss/snowflakes/homepage.scss
- styleguide/_themes/global/scss/banners.scss
- styleguide/_themes/global/scss/buttons.scss
- styleguide/_themes/global/scss/vendor_prefixes.scss
- styleguide/derek/_partials/solutions/header-mediumIMAC.ejs
- styleguide/derek/_partials/solutions/header-smallIMAC.ejs
- styleguide/derek/assets/photography.jade
- styleguide/derek/examples/homepage.ejs
- styleguide/derek/examples/imac.jade
- styleguide/derek/examples/index.jade
- styleguide/derek/examples/landing-page.ejs
https://jira.rax.io/browse/RSWEB-6941
> feat(zoolander):imac-banners

- styleguide/_themes/global/scss/banners.scss
- styleguide/derek/_partials/solutions/header-largeIMAC.ejs
- styleguide/derek/_partials/solutions/header-mediumIMAC.ejs
- styleguide/derek/_partials/solutions/header-smallIMAC.ejs
- styleguide/derek/examples/imac.jade
> bug(imac):fixing the line class

- styleguide/_themes/derek/scss/globalElements/ceilingLp.scss
https://jira.rax.io/browse/RSWEB-7036
The issue was that the link had 0 height.
> bug(zoolander): fixed logo link issue for landing pages

- .sass-lint.yml
- styleguide/_themes/derek/scss/components/subnav.scss
- styleguide/_themes/derek/scss/globalElements/basement.scss
- styleguide/_themes/derek/scss/globalElements/ceilingLp.scss
- styleguide/_themes/global/scss/fonts.scss
- styleguide/css/main.scss
- styleguide/derek/_partials/_ceilingLp.ejs
- styleguide/derek/_partials/_footerLp.ejs
- styleguide/derek/_partials/solutions/subnav.ejs
- styleguide/derek/examples/landing-page.ejs
https://jira.rax.io/browse/RSWEB-6972
Adding landing page version of footer and adjusting ceiling to include title.
> feat(landing-page):adjusting global elements

- styleguide/js/zoolander.js
https://jira.rax.io/browse/RSWEB-7138
> fix(nav): rsweb-7138 Nav Fix

- styleguide/_themes/global/scss/forms.scss
- styleguide/derek/assets/forms.ejs
> styling(forms): Added www modal forms to zoolander

- styleguide/_themes/derek/scss/patterns/grid/businessResource.scss
- styleguide/_themes/derek/scss/patterns/grid/ias.scss
- styleguide/_themes/derek/scss/patterns/grid/keyOffers.scss
- styleguide/_themes/global/scss/fonts.scss
- styleguide/derek/_partials/grid/widget/business-resource-no-hover.ejs
- styleguide/derek/_partials/grid/widget/key-offer-no-hover.ejs
- styleguide/derek/_partials/grid/widget/key-offer.ejs
- styleguide/derek/_partials/solutions/business-resources.ejs
- styleguide/derek/_partials/solutions/key-offers.ejs
This PR is in lieu of #211, since I didn't have write access to Sam's repo and needed to make a few tweaks. I left his original commit intact so we can monitor the incremental changes.
> RSWEB-6910: Fix grid hoverstate

- styleguide/_themes/derek/scss/patterns/grid/keyOffers.scss
This PR fixes the zoolander-side of the key offer bug.
> RSWEB-7204: Fixes equal height on key offers

- styleguide/_themes/derek/scss/patterns/lead.scss
- styleguide/_themes/derek/scss/patterns/subpanels.scss
Updates text alignment for leads.
http://localhost:9000/derek/examples/subpanels
> RSWEB-7231: leads text alignment

- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/derek/scss/patterns/grid/valueProp.scss
- styleguide/derek/_partials/solutions/value-prop.ejs
Updates padding for value props.
> RSWEB-7224: update padding for value props

- styleguide/_themes/derek/scss/patterns/videoEmbed.scss
This PR removes the left push from the video and sets the width to 100%.
> RSWEB-7226: make video full width

- styleguide/_themes/derek/scss/patterns/grid/ias.scss
- styleguide/_themes/derek/scss/patterns/grid/keyOffers.scss
- styleguide/_themes/global/scss/tables.scss
Changes viewable on:
http://localhost:9000/derek/examples/tables
http://localhost:9000/derek/examples/solutions
Looking for hover color correction on key offers and i&s patterns as well as icon color on key offers and reverting color adjustments on tables.
https://jira.rax.io/browse/RSWEB-7228
> bug(zoolander):fix-color-inconsistenceies

- package.json
- styleguide/_themes/derek/scss/components/subnav.scss
- styleguide/_themes/global/scss/bootstrap_overrides.scss
- styleguide/derek/_partials/solutions/subnav.ejs
- styleguide/derek/examples/office365.ejs
https://jira.rax.io/browse/RSWEB-7047
Subnav reformat and mobile fix can be seen here:
http://localhost:9000/derek/examples/office365
Looking for better mobile performance and issue fixes around these areas:
- incorrect breakpoints
- page title display issues in mobile
- exploring another active state for mobile menu
There has also been pretty significant reformatting of the code which will need a www PR for implementation.
> bug(mobile):subnav fixes

- styleguide/_themes/derek/scss/components/subnav.scss
Updates padding for the subnav when in larger viewports (>1200px width).
View on this page locally. http://localhost:9000/derek/examples/office365
> RSWEB-7250: update subnav padding for larger viewports

- styleguide/_themes/derek/scss/globalElements/mainnav.scss
> RSWEB-7276: fixed hover state on dropdown labels

- styleguide/_themes/global/scss/buttons.scss
No JIRA ticket. High priority button fix for IMAC. Looking for reducing the padding on buttons from 15px padding top/bottom to 8px padding top/bottom.
> bug(zoolander):padding

- styleguide/_themes/derek/scss/globalElements/ceiling.scss
- styleguide/_themes/derek/scss/globalElements/mainnav.scss
- styleguide/derek/_partials/_mainnav.ejs
- styleguide/js/zoolander.js
Swapped dropdown-toggle class for something more maintainable. Added in drop down carets for ceiling login/signup buttons.
> RSWEB-7325: added maintainable classes for dropdown carets

- styleguide/_layouts/default.jade
- styleguide/css/main.scss
- styleguide/js/zoolander.js
Adding this improvement into Amber's ticket: 7276
> RSWEB-7348 (formerly RSWEB-6905): side nav improvements

- styleguide/_themes/derek/scss/patterns/videoEmbed.scss
This PR fixes video inside of flexboxes.
> RSWEB-7358: Fix video inside flexbox

- styleguide/_themes/derek/scss/patterns/videoEmbed.scss
This PR addresses the missing video issue.
> RSWEB-7358 [www] Videos not showing after panel updates

- styleguide/_themes/global/scss/fonts.scss
- styleguide/derek/_partials/cards/additional-resource.ejs
- styleguide/derek/_partials/cards/announcements.ejs
- styleguide/derek/_partials/cards/ias-no-hover.ejs
- styleguide/derek/_partials/cards/ias.ejs
- styleguide/derek/_partials/cards/key-offer-no-hover.ejs
- styleguide/derek/_partials/cards/key-offer.ejs
- styleguide/derek/_partials/cards/list.ejs
- styleguide/derek/_partials/cards/product-feature.ejs
- styleguide/derek/_partials/cards/value-prop.ejs
- styleguide/derek/_partials/solutions/cta.ejs
- styleguide/derek/_partials/solutions/quote.ejs
- styleguide/derek/_partials/solutions/tabs.ejs
- styleguide/derek/_partials/solutions/testimonials.ejs
- styleguide/derek/_partials/solutions/video.ejs
- styleguide/derek/examples/_data.json
- styleguide/derek/examples/layouts/additional-resources.ejs
- styleguide/derek/examples/layouts/announcements.ejs
- styleguide/derek/examples/layouts/features.ejs
- styleguide/derek/examples/layouts/ias.ejs
- styleguide/derek/examples/layouts/key-offers.ejs
- styleguide/derek/examples/layouts/lists.ejs
- styleguide/derek/examples/layouts/value-props.ejs
- styleguide/derek/examples/solutions-usage.ejs
- styleguide/derek/examples/solutions.ejs
RSWEB-7353
Creating patterns documentation for our available patterns.
Viewable here: http://localhost:9000/derek/examples/solutions-usage
and linked to from here: http://localhost:9000/derek/examples/solutions
Looking for clear and concise documentation but not many changes to actual patterns other than adjusting dummy text to be within character limits.
> RSWEB-6905: zoolander documentation

- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/derek/scss/patterns/cards/awards.scss
- styleguide/derek/_partials/cards/awards.ejs
- styleguide/derek/examples/layouts/awards.ejs
- styleguide/derek/examples/solutions-usage.ejs
- styleguide/derek/examples/solutions.ejs
RSWEB-7416
Looking to add in the awards card. Need the scss for the imac pages.
Can be viewed either here:
http://localhost:9000/derek/examples/solutions
Or here with documentation:
http://localhost:9000/derek/examples/solutions-usage
Will attach an image or what it should look like. Just without the background image.
> RSWEB-7416: awards-pattern

- styleguide/_themes/derek/scss/components/regionSelector.scss
- styleguide/derek/_partials/_regionSelector.ejs
Updates Region Selector close button.
> RSWEB-7335: close button on region selector

- styleguide/derek/_partials/cards/ias-no-hover.ejs
- styleguide/derek/_partials/cards/ias.ejs
Updates IAS pattern on the solutions page to be consistent with the counterpart on www. 
**Will not require a www counterpart and has no affect on the live site.** 
http://localhost:9000/derek/examples/solutions
> RSWEB-7368: center img on ias pattern

- styleguide/_themes/global/scss/banners.scss
> imac banner things again

- styleguide/_themes/derek/scss/globalElements/mainnav.scss
This PR adjusts search button size to fix issues with spanish.
> RSWEB-7467: [bug] Adjust size of search button

- styleguide/_themes/derek/scss/patterns/cards/productFeatures.scss
This PR adjusts font size for the rsweb icon on features.
> RSWEB-7499: [bug] Adjusts font size to fit inside smaller container

- styleguide/derek/examples/subpanels.ejs
This PR fixes announcements on subpanels page.
> RSWEB-7551: Fixes announcement pattern on subpanels

- styleguide/_themes/derek/scss/globalElements/mainnav.scss
Removes persisting visited state in nav.
http://localhost:9000/derek/examples/section-overview
> RSWEB-7460: remove background color for active dropdown link

- styleguide/_themes/derek/scss/patterns/announcements.scss
- styleguide/_themes/derek/scss/patterns/panels.scss
- styleguide/derek/_partials/cards/announcements-link.ejs
- styleguide/derek/_partials/cards/announcements.ejs
- styleguide/derek/examples/layouts/announcements.ejs
Needs design/code review. Added a header option and wrapped linked announcements in a custom a tag.
> RSWEB-7529: pattern(announcement): added header and hover state if link

- package.json
- styleguide/_themes/derek/scss/snowflakes/homepage.scss
- styleguide/_themes/global/scss/forms.scss
This PR clears up 9 sass lint errors related to white space.
> chore(rsweb-7088-sass-lint-white-space): cleanup white space errors

- styleguide/_themes/derek/scss/patterns/blog-feed.scss
- styleguide/derek/_partials/solutions/blog-feed.ejs
This PR fixes the equal height containers on blogs.
> RSWEB-7701: Fixes equal height containers on blog items

- styleguide/_themes/derek/scss/patterns/cards/productFeatures.scss
Remove unneeded margin on features pattern in mobile.
http://local.rackspace.com:7080/openstack/private/enablement
> RSWEB-7579: remove uneeded margin mobile

- styleguide/_themes/derek/scss/globalElements/mainnav.scss
- styleguide/_themes/global/scss/bootstrap_overrides.scss
- styleguide/js/zoolander.js
- Allows users to click on tertiary nav when at exactly 768px
- Aligns tertiary nav to be flush with secondary nav in tablet view
ex: http://localhost:9000/derek/examples/section-overview
WWW counterpart - https://github.rackspace.com/rswebteam/www/pull/1355
> RSWEB-7476: cleanup nav issues in tablet and mobile

- .sass-lint.yml
Updates to sass lint introduced a new bug.
> RSWEB-7794: Fixes bug in sass lint

- styleguide/_themes/derek/scss/snowflakes/stories.scss
- styleguide/derek/examples/stories-interior.ejs
- styleguide/derek/examples/stories.ejs
This PR makes some minor pre-launch changes to stories. 
- **Reordered content per Mike:**  This required `story-video` class addition to prevent video from filling up entire right column. 
- **Removed industry filter**
> RSWEB-7795: Story prelaunch preparations. 

- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/derek/scss/globalElements/ext-links.scss
- styleguide/derek/_partials/_footer.ejs
- styleguide/derek/_partials/_mainnav.ejs
- styleguide/derek/_partials/solutions/ext-link.ejs
- styleguide/derek/examples/solutions.ejs
Added the class for the external link icon. Once brought in, we can add them to the needed links in Drupal.
> RSWEB-7668 feat(zoolander): added class for external links

- package.json
- styleguide/_themes/derek/scss/patterns/cards/modules.scss
This PR removes the max height from the customer logos
> RSWEB-7824: Remove max height

- styleguide/derek/_partials/_rug.ejs
I've altered the code to remove the `sm` breakpoint altogether as we have `hidden-sm` declared on the rug. 
Then I just set different breakpoints for `md` vs `lg`.
> RSWEB-7824: (1280) Adjust rug breakpoints

- styleguide/_themes/derek/scss/components/subnav.scss
- styleguide/_themes/derek/scss/globalElements/basement.scss
- styleguide/_themes/derek/scss/globalElements/ceiling.scss
- styleguide/_themes/derek/scss/globalElements/footer.scss
- styleguide/_themes/derek/scss/globalElements/mainnav.scss
- styleguide/_themes/derek/scss/globalElements/rug.scss
- styleguide/_themes/derek/scss/modifiers.scss
- styleguide/_themes/derek/scss/patterns/announcements.scss
- styleguide/_themes/derek/scss/patterns/cards/productFeatures.scss
- styleguide/_themes/derek/scss/patterns/cards/resources.scss
- styleguide/_themes/derek/scss/snowflakes/homepage.scss
- styleguide/_themes/global/scss/bootstrap_variables.scss
- styleguide/_themes/global/scss/global.scss
- styleguide/_themes/global/scss/grid.scss
- styleguide/_themes/global/scss/modifiers.scss
- styleguide/derek/_partials/_basement.ejs
- styleguide/derek/_partials/_footer.ejs
- styleguide/derek/_partials/_footerLp.ejs
- styleguide/derek/examples/homepage.ejs
This is the release branch for 1280
> 1280 release branch

- styleguide/_themes/derek/scss/components/regionSelector.scss
- styleguide/derek/_partials/_basement.ejs
This PR fixes the region selector issues for 1280.
> RSWEB-7791: Fixes region selector for 1280

- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/derek/scss/patterns/cards/ias.scss
- styleguide/_themes/derek/scss/patterns/cards/valueProp.scss
- styleguide/_themes/global/scss/fonts.scss
Updates body text alignment for ias and value props pattern to be centered.
Goes with www PR https://github.rackspace.com/rswebteam/www/pull/1396
Example pages on local www
- http://local.rackspace.com:7080/cloud/orchestration
- http://local.rackspace.com:7080/node/7366
> RSWEB-7703: center body text on ias and vp patterns

- styleguide/_themes/derek/scss/globalElements/basement.scss
This PR fixes the region selector on mobile by pushing the text into multiple lines instead of trying to stack them in a small space.
> RSWEB-7868: Make region selector great again

- package.json
- styleguide/_themes/derek/scss/snowflakes/homepage.scss
- styleguide/_themes/global/scss/fonts.scss
Kills a few sass lint errors related to pseudo elements.
> RSWEB-7084: Pseudo Element Nesting

- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/derek/scss/components/pager.scss
- styleguide/derek/incubation/stories.ejs
This PR adds some basic pagination style, specifically for the customer stories page, but will probably get used in the updated search results page and more in the future.
> RSWEB-7874: Add pagination style

- package.json
- styleguide/_themes/derek/scss/snowflakes/homepage.scss
- styleguide/_themes/derek/scss/snowflakes/swatches.scss
- styleguide/_themes/global/scss/fonts.scss
- styleguide/_themes/global/scss/vendor_prefixes.scss
This PR fixes @extend and vendor prefix related sass lint errors.
> RSWEB-7089: Fix extend/vendor prefixes sass lint errors

- styleguide/_themes/derek/scss/snowflakes/events.scss
- styleguide/derek/incubation/events-interior.ejs
- styleguide/derek/incubation/events.ejs
This PR removes the old events banner and adds an IMAC banner instead.
> RSWEB-7445: Add imac banner

- styleguide/derek/incubation/stories-interior.ejs
This PR adjusts the content order on the stories page.
> RSWEB-7879: Adjust content order

- styleguide/_themes/derek/scss/globalElements/mainnav.scss
- styleguide/_themes/global/scss/fonts.scss
- styleguide/derek/_partials/solutions/ext-link.ejs
This PR fixes styles on p tags.
> RSWEB-7872: Fixes styles on p tags

- styleguide/_themes/derek/scss/globalElements/ext-links.scss
This PR removes the underline from the extlink.
> RSWEB-7829: Remove underline from extlink

- styleguide/_themes/global/scss/rsweb-font-style.scss
> feat(rsweb): use sass map for rsweb icon classes

- styleguide/_themes/global/scss/buttons.scss
Previewable here:
http://localhost:9000/derek/assets/buttons
and here
http://localhost:9000/derek/incubation/homepage
> rsweb-7844-button-text

- styleguide/_layouts/default.jade
- styleguide/_themes/derek/scss/components/subnav.scss
- styleguide/_themes/derek/scss/globalElements/ceiling.scss
- styleguide/_themes/derek/scss/globalElements/mainnav.scss
- styleguide/_themes/derek/scss/globalElements/rug.scss
- styleguide/_themes/derek/scss/patterns/announcements.scss
- styleguide/_themes/derek/scss/patterns/cards/awards.scss
- styleguide/_themes/derek/scss/patterns/cards/keyOffers.scss
- styleguide/_themes/derek/scss/patterns/cards/productFeatures.scss
- styleguide/_themes/derek/scss/patterns/lead.scss
- styleguide/_themes/global/scss/bootstrap_variables.scss
- styleguide/_themes/global/scss/fonts.scss
style(fonts):removing 300 font weight, increasing line height and base font height.
Can be previewed across the styleguide. Should check here:
http://localhost:9000/derek/solutions/solutions 
and here:
http://localhost:9000/derek/assets/typography
> RSWEB-7802: Remove 300 font weight, and increase line-height/base font height.

- styleguide/_themes/derek/scss/globalElements/ceilingLp.scss
- styleguide/_themes/derek/scss/patterns/cards/ias.scss
- styleguide/_themes/derek/scss/patterns/cards/productFeatures.scss
- styleguide/_themes/derek/scss/patterns/cards/valueProp.scss
- styleguide/derek/_partials/cards/ias.ejs
- styleguide/derek/_partials/cards/value-prop.ejs
This PR fixes some issues found with the latest font weight and line height changes. 
This requires a www ticket as well.
> RSWEB-8061: Fix line-height and font related issues

- styleguide/_themes/global/scss/forms.scss
Needs to be deployed with https://github.rackspace.com/rswebteam/www/pull/1481
> RSWEB-7725: add thobber classes for ajax form submissions

- styleguide/_themes/derek/scss/patterns/cards/awards.scss
- styleguide/_themes/derek/scss/patterns/panels.scss
RSWEB-8089
bug(styleguide):fixing broken images in firefox
Testable on https://www.rackspace.com/office-365
Not sure of testable styleguide links.
> RSWEB-8089 broken images in firefox

- styleguide/_themes/derek/scss/globalElements/ceiling.scss
This PR adds a cursor to the ceiling links
> RSWEB-7735: Adds cursor to ceiling links

- styleguide/_themes/derek/scss/patterns/videoEmbed.scss
https://jira.rax.io/browse/RSWEB-8434
> RSWEB-8434: Put the youtube iframe in a wrapper.

- styleguide/_themes/derek/scss/patterns/videoEmbed.scss
This PR adds a little bit of padding under the video embed.
> RSWEB-8434: Add margin under video embed

- styleguide/_themes/derek/scss/patterns/cards/productFeatures.scss
- styleguide/derek/_partials/cards/product-feature.ejs
- styleguide/derek/layouts/features.ejs
- styleguide/derek/solutions/solutions-usage.ejs
Updates feature pattern to better use common css class naming convention.
- removes nested classes from wrapper class
- sets underline for links on the features pattern to the `.feature-bodyWrapper` class so that links are not dependent on the global `p > a` style assignment
http://localhost:9000/derek/solutions/solutions
> RSWEB-8025: refactor features pattern

- styleguide/_themes/global/scss/tables.scss
> RSWEB-8304: refactor(tables): Changed header font size and bg color

- styleguide/_themes/global/scss/banners.scss
- styleguide/derek/assets/photography.jade
RSWEB-8536
Updating Banner documentation
Can be seen here:
http://localhost:9000/derek/assets/photography
> rsweb-8536-banner-documentation

- .sass-lint.yml
- styleguide/_themes/global/scss/global.scss
- styleguide/_themes/global/scss/scaffolding.scss
This PR moves scaffolding into the repo.
Note, this is a prerequisite for #371
> RSWEB-8518: Move scaffolding into repo

- styleguide/_themes/global/scss/buttons.scss
- styleguide/derek/assets/buttons.jade
RSWEB-8490
Restyling leaving button style to be login style also to serve dual purposes in the CMS
Adjust line-height and padding so all buttons are the same height
Visible here:
http://localhost:9000/derek/assets/buttons
> rsweb-8490-login/leaving-buttons

- styleguide/_themes/derek/scss/patterns/cards/productFeatures.scss
RSWEB-8542
Improving features pattern to include
-Removing increased font size for h3
-Removing media in mobile
-Removing teal hover state for links and bolding those
Visible here:
http://localhost:9000/derek/solutions/solutions-usage
Under features
> rsweb-8542-improve-features

- styleguide/_themes/global/scss/modifiers.scss
- styleguide/_themes/global/scss/scaffolding.scss
- styleguide/derek/_partials/solutions/rivers.ejs
- styleguide/derek/assets/swatches.ejs
RSWEB-8518
Adjusting horizontal rule to reduce margins.
Add red option for horizontal rule
Add red border option for background
Add documentation or horizontal rule and red border background 
Viewable here:
http://localhost:9000/derek/assets/swatches
> rsweb 8518 adjust hr

- styleguide/_themes/derek/scss/globalElements/rug.scss
- styleguide/_themes/global/scss/rsweb-font-style.scss
- styleguide/_themes/global/scss/vendor_prefixes.scss
- styleguide/derek/_partials/_rug.ejs
- styleguide/derek/_partials/cards/quote.ejs
- styleguide/derek/incubation/homepage.ejs
Viewable at the bottom of the homepage:
http://localhost:9000/derek/incubation/homepage
Looking to replace the rug with something a little more useful. Images are in the ticket.
> rsweb-8229-deloitte-rug

- styleguide/_themes/derek/scss/globalElements/rug.scss
RSWEB-8719 
Adjusting alignment on the rug to match the footer
> rsweb-8719-adjust-rug

- styleguide/_themes/derek/scss/patterns/quote.scss
- styleguide/derek/_partials/solutions/quote.ejs
- styleguide/derek/layouts/quote-split.ejs
This PR makes some changes to the quote pattern to permit usage in mini panels.
> RSWEB-8764: Make quotes work in mini panels

- styleguide/_themes/derek/scss/globalElements/ceiling.scss
- styleguide/_themes/derek/scss/globalElements/mainnav.scss
- styleguide/derek/_partials/_mainnav.ejs
RSWEB-8714
Decreasing font size and adding partners into the navigation
Can be viewed on http://localhost:9000/derek/incubation/homepage
Please open search to test breakpoints fully
> rsweb-8714-reduce-nav-font-size

- styleguide/_themes/derek/scss/globalElements/ceiling.scss
- styleguide/_themes/derek/scss/globalElements/mainnav.scss
- styleguide/derek/_partials/_ceiling.ejs
RSWEB-8689
Reproducing the "app style" icons on mobile in the ceiling.
Removing the text, increasing the size of the icons.
> rsweb-8689-app-style-icons

- styleguide/_themes/derek/scss/patterns/panels.scss
- styleguide/_themes/derek/scss/snowflakes/swatches.scss
- styleguide/_themes/global/scss/modifiers.scss
- styleguide/derek/_partials/solutions/rivers.ejs
- styleguide/derek/assets/swatches.ejs
- styleguide/derek/solutions/subpanels.ejs
RSWEB-8500
Removal of bgs both in rivers and subpanels of:
- Teal
- Blue Steel
- Crumpled Paper
- Red
> rsweb-8500-removeBGs-paddingPOC

- .eslintrc.js
- .travis.yml
- hooks
- styleguide/global/global.js
This PR cleans up bad javascript and integrates travis for javascript linting.
> RSWEB-8876: Cleanup Javascript + Integrate Travis

- package.json
This should fix the ci issue.  Not sure why it just randomly started complaining about it now, but either way, here it is for testing.
> RSWEB-8843: Fixes dependency issue

- styleguide/_layouts/default.jade
- styleguide/global/contributing.jade
- styleguide/global/styleguide.jade
- styleguide/index.jade
RSWEB-8781
Adding code contribution, standards and dev workflow documentation page.
Can be viewed here:
http://localhost:9000/global/contributing 
as well as within the main navigation under "Home" and on the welcome page as a link.
> docs(global): add code standards

- styleguide/derek/_partials/typography/heading.ejs
- styleguide/derek/_partials/typography/subhead.ejs
- styleguide/derek/assets/buttons.jade
- styleguide/derek/assets/typography.jade
- styleguide/global/brand-elements.jade
- styleguide/global/voice.jade
RSWEB-8784
Cleaning up some incorrect documentation.
Creating a separate task for the icons since it's going to require some work and hopefully we can move over the assets for that at that time.
> docs(global):cleanup docs

- styleguide/derek/global-components/basement/_basement.scss
- styleguide/derek/global-components/basement/basement.ejs
Adds currency selector styles and markup to basement template for consistency across web properties.
http://rsweb-6759-currency-basement-selector.www.dev.website.rackspace.com/openstack/public/service-levels
> RSWEB-6759: add currency selector

- styleguide/_themes/derek/scss/_main.scss
- styleguide/derek/incubation/index.jade
- styleguide/derek/pattern-components/images/image.ejs
- styleguide/derek/pattern-components/leads/lead-image/lead-image.ejs
- styleguide/derek/pattern-components/leads/lead/lead.ejs
- styleguide/derek/pattern-components/text/text.ejs
- styleguide/derek/view-templates/leadership/_data.json
- styleguide/derek/view-templates/leadership/_layout.jade
- styleguide/derek/view-templates/leadership/_leadership-individual.ejs
- styleguide/derek/view-templates/leadership/_leadership.scss
- styleguide/derek/view-templates/leadership/leadership-interior.ejs
- styleguide/derek/view-templates/leadership/leadership.ejs
RSWEB-8768
http://localhost:3000/derek/incubation/
Viewable by clicking "Leadership Overview" Link
Adding views for leadership overview and interior page
Overview page needed images, name and title and a link to the interior page
Interior page needed image, name, title, link back to overview page and bio
Made adjustments to text partial and image partial in order to be able to support the view. They are minimal and won't effect www.
> feat(derek): Add leadership views

- styleguide/_themes/derek/scss/_main.scss
- styleguide/derek/pattern-components/resourceCenter-resource/_partials/resourceCenter-resource.ejs
- styleguide/derek/pattern-components/resourceCenter-resource/_resourceCenter-resource.scss
- styleguide/derek/pattern-components/resourceCenter-resource/resourceCenter-resource.ejs
- styleguide/derek/solutions/solutions-usage.ejs
RSWEB-8629
Refactoring and revamping the resources pattern.
I've made the pattern maintainable and chosen maintainable classes for the icons to avoid conflicts.
The EBPs should still just be able to choose the same classes, we can just fill them into the middle of the class.
This is viewable on any page that has resources on it but I used this one:
http://localhost:3000/derek/templates/product/product-overview
Please review in mobile and with the hover state as well.
> refactor(derek): revamp resources pattern

- styleguide/derek/pattern-components/resourceCenter-resource/_resourceCenter-resource.scss
- styleguide/derek/pattern-components/resourceCenter-resource/resourceCenter-resource.ejs
This PR is a half way step between #445 which was already merged and #448 which has yet to be merged.  This is needed to correct some class related issues that happened in between these two steps, but are needed to be resolved independently of that other work.
> fix(resource-center): Adjust icons colors

- styleguide/_themes/global/scss/modifiers.scss
- styleguide/derek/global-components/subnav/_subnav.scss
Note this is tied to a www pr
Change summary:
- Add new class for styling body region
- Remove margin from nav bar
> refactor(nav): Remove margin from nav and add padding to body.

- styleguide/_themes/global/scss/modifiers.scss
> fix(css): Adjust issue with padding rule.

- styleguide/derek/pattern-components/resourceCenter-resource/resourceCenter-resource.ejs
- styleguide/derek/view-templates/resource-center/_partials/all-resources.ejs
- styleguide/derek/view-templates/resource-center/_partials/resource.ejs
- styleguide/derek/view-templates/resource-center/_resource-center.scss
- styleguide/derek/view-templates/resource-center/code.ejs
- styleguide/derek/view-templates/resource-center/docs.ejs
- styleguide/derek/view-templates/resource-center/pdf-image.ejs
- styleguide/derek/view-templates/resource-center/pdf.ejs
- styleguide/derek/view-templates/resource-center/video.ejs
- styleguide/derek/view-templates/resource-center/webinar.ejs
This PR adjusts the views templates to play nicely with Drupal.
> RSWEB-9127: Adjust templates to play nicely with Drupal

- styleguide/_themes/derek/scss/_main.scss
- styleguide/derek/pattern-components/service-level-teaser/_partials/teaser.ejs
- styleguide/derek/pattern-components/service-level-teaser/_service-level-teaser.scss
- styleguide/derek/pattern-components/service-level-teaser/service-level-teaser.ejs
- styleguide/derek/solutions/solutions.ejs
Addition of Service level teaser pattern.
Seen here: 
http://localhost:3000/derek/solutions/solutions
> RSWEB-8951 feat(newpattern): addition of service level teaser

- styleguide/derek/global-components/filter-bar/_filter-bar.scss
- styleguide/derek/view-templates/resource-center/_partials/checkbox.ejs
- styleguide/derek/view-templates/resource-center/resource-center.ejs
This PR makes a few minor tweaks to the filter overview to play nicely with Drupal.
> RSWEB-8637: Adjust filters to address Drupalisms

- styleguide/_themes/global/scss/buttons.scss
Change summary:
- update learning button css
> refactor(button): update learning button style

- styleguide/derek/view-templates/resource-center/_resource-center.scss
This PR adds alternative icons for the featured build modes.
> RSWEB-9269: Add alternate icon for featured build modes

- .travis.yml
- npm-shrinkwrap.json
- package.json
This PR tests adding node 6 into the travis mix
> RSWEB-9122: Add node 6 to Travis

- styleguide/derek/global-components/basement/_basement.scss
- styleguide/derek/global-components/basement/basement.ejs
preview: can be seen here
http://localhost:3000/derek/incubation/homepage
> RSWEB-9125 feat(basement): added third column for statement

- styleguide/derek/view-templates/events/_events.scss
> fix(bug fix): Change button text from black to white

- styleguide/derek/global-components/tracking/tracking.js
- styleguide/derek/global-components/tracking/tracking.spec.js
https://jira.rax.io/browse/RSWEB-9097
> RSWEB-9097: Add tracking to filtering

- karma.conf.js
- package.json
- styleguide/derek/global-components/filter-bar/filter-bar.js
- styleguide/derek/global-components/filter-bar/filter-bar.spec.js
Break up filterJs a bit to allow for unit testing.
Add unit tests.
Based tests on what the values come out to when you change the size of the window and whether youre scrolled down or not.
> Filterjs unit tests

- styleguide/derek/pattern-components/ctas/cta-bottom.ejs
- styleguide/derek/pattern-components/ctas/cta.ejs
- styleguide/derek/patterns/patterns.ejs
RSWEB-9073
Visible here:
http://localhost:3000/derek/solutions/solutions-usage
Adding documentation around what patterns have events within zoolander and what those events are. This is everything that we found in discovery with data.
> docs(derek): add pattern event tracking doc

- styleguide/_themes/derek/scss/_main.scss
- styleguide/derek/incubation/index.jade
- styleguide/derek/view-templates/search/_data.json
- styleguide/derek/view-templates/search/_layout.jade
- styleguide/derek/view-templates/search/_search-result.ejs
- styleguide/derek/view-templates/search/_search.scss
- styleguide/derek/view-templates/search/search.ejs
https://jira.rax.io/browse/RSWEB-9346
> RSWEB-9346: Search result styles

- styleguide/_themes/global/scss/buttons.scss
- styleguide/derek/global-theme/buttons.jade
- styleguide/derek/pattern-components/quotes/_partials/quote.ejs
- styleguide/derek/pattern-components/quotes/_quotes.scss
RSWEB-9301
Should Mirror: RSWEB-9243
Visible here:
http://localhost:3000/derek/patterns/patterns in quote pattern
Addition of ghost button is visible here:
http://localhost:3000/derek/global-theme/buttons
> style(global): ghost button on quote

- karma.conf.js
- styleguide/derek/global-components/anchor-scroll/anchor-scroll.js
- styleguide/derek/global-components/anchor-scroll/anchor-scroll.spec.js
- styleguide/derek/view-templates/stories/_stories.scss
- styleguide/derek/view-templates/stories/stories.ejs
- styleguide/global/global.js
You can see it in action locally here
http://localhost:3000/derek/view-templates/stories/stories
> RSWEB-9334 feat(new-pattern): added 3 featured customer stories to its homepage

- styleguide/derek/view-templates/events/_events.scss
RSWEB-9320
Adjusting the colors on the internal events page to remove teal.
Visible here:
http://localhost:3000/derek/view-templates/events/events
> style(derek): adjust events colors

- styleguide/derek/pattern-components/additional-resources/_partials/additional-resource.ejs
- styleguide/derek/pattern-components/resourceCenter-resource/_partials/resourceCenter-resource.ejs
- styleguide/derek/pattern-components/resourceCenter-resource/_resourceCenter-resource.scss
- styleguide/derek/patterns/patterns.ejs
@writes here is the quick fix for the condensed resource.
> fix(derek): Adjust condensed resource

- styleguide/derek/view-templates/stories/stories.ejs
Updated filtering section for customer stories page.
> feat(derek): update filtering on stories page

- styleguide/derek/global-components/tracking/tracking.js
- styleguide/derek/global-components/tracking/tracking.spec.js
Add different event for call trigger.
> feat(tracking): Add call cta tracking

- styleguide/derek/view-templates/resource-center/_partials/resource.ejs
- styleguide/derek/view-templates/resource-center/_resource-center.scss
Added conditional classes to our markup for video resources only
> fix(resources): conditional video classes add for resource page html

- styleguide/derek/view-templates/stories/_stories.scss
> fix(bug): customer stories feature quote was broken in non chrome

- styleguide/derek/global-theme/photography.jade
- styleguide/derek/pattern-components/leads/_lead.scss
- styleguide/derek/pattern-components/leads/lead/lead.ejs
Links in a bullet list need to look like links.
> bug(links): Links in bullet lists need to look like links.

- styleguide/_layouts/default.jade
- styleguide/derek/incubation/homepage.ejs
- styleguide/derek/incubation/refresh.jade
- styleguide/derek/pattern-components/headers/_headers.scss
- styleguide/derek/pattern-components/headers/header-refresh-homepage.ejs
- styleguide/derek/pattern-components/headers/header-refresh.ejs
For review:
http://rsweb-9534-homepage.styleguide.dev.website.rackspace.com/derek/incubation/homepage
> RSWEB-9534: New Homepage Banner

- styleguide/derek/pattern-components/headers/_headers.scss
- styleguide/derek/pattern-components/headers/header-refresh.ejs
Adjusted the height for the interior banners and made the img paths relative.
> bug(derek): Quick LP Fixes

- styleguide/_themes/derek/scss/_main.scss
- styleguide/derek/incubation/homepage.ejs
- styleguide/derek/pattern-components/platforms/_partials/platform.ejs
- styleguide/derek/pattern-components/platforms/_platforms.scss
- styleguide/derek/pattern-components/platforms/platforms.ejs
RSWEB-9541
Creating a new nascar river to mirror design linked in the ticket. Only weirdness is that I had to create an override for super small screens to go full width. I also took out legacy example code on the homepage that is no longer there so we can have a proper stakeholder review.
This can be seen here:
http://localhost:3000/derek/incubation/homepage
beneath the announcement section (which isn't the final version but I needed to see it on page)
> feat(derek): add nascar river

- styleguide/_themes/global/scss/vendor_prefixes.scss
- styleguide/derek/pattern-components/lp-callout/_lp-callout.scss
- styleguide/derek/pattern-components/lp-callout/gc-callout-form/gc-callout.ejs
- styleguide/derek/pattern-components/lp-callout/lp-callout-chat/lp-callout.ejs
- styleguide/derek/pattern-components/lp-callout/lp-callout-form/lp-callout.ejs
- styleguide/derek/templates/landing-page/landingpage-form.ejs
- styleguide/derek/view-templates/resource-center/_data.json
- styleguide/derek/view-templates/resource-center/_partials/resource-gated.ejs
- styleguide/derek/view-templates/resource-center/_resource-center.scss
- styleguide/derek/view-templates/resource-center/pdf-gated.ejs
- styleguide/imgs/derek/resourceCenter/gated-arrow.svg
RSWEB-9573
Added gated content layout.
Also adjusted the callout to be more efficient and less spaghetti.
Can be viewed here:
http://localhost:3000/derek/view-templates/resource-center/pdf-gated
and pages effected by callout adjustment:
http://localhost:3000/derek/templates/landing-page/landingpage-form
http://localhost:3000/derek/templates/landing-page/landingpage-chat
> feat(derek): add gated content

- karma.conf.js
- styleguide/derek/global-components/social/_social.scss
- styleguide/derek/global-components/social/social-tracking.js
- styleguide/derek/global-components/social/social-tracking.spec.js
- styleguide/derek/global-components/social/social.ejs
Needs to be used with https://tagmanager.google.com/?authuser=0#/container/accounts/150065697/containers/1780062/workspaces/551?orgId=PAGSMOJSQzSi4wc-uWGbig
Also, according to this documentation Google+ does not need any custom tracking.
https://developers.google.com/analytics/devguides/collection/analyticsjs/social-interactions#google
> RSWEB-9481: Social tracking

- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/derek/scss/snowflakes/homepage.scss
- styleguide/derek/incubation/homepage.ejs
- styleguide/derek/pattern-components/platforms/_partials/platform.ejs
- styleguide/derek/pattern-components/platforms/_platforms.scss
- styleguide/derek/pattern-components/platforms/platforms.ejs
RSWEB-9719
Cleaning up the styling on homepage to make sure all elements play nice together.
Visible here: 
http://localhost:3000/derek/incubation/homepage
> refactor(derek): Cleanup homepage styling

- styleguide/derek/pattern-components/resourceCenter-resource/refresh/_partials/resourceCenter-resource.ejs
- styleguide/derek/pattern-components/resourceCenter-resource/refresh/_resourceCenter-resource.scss
- styleguide/derek/pattern-components/resourceCenter-resource/refresh/resourceCenter-resourceRow2.ejs
RSWEB-9812
Creating a webinar card for the resource center. 
Should look just like the pdf card but with the webinar icon instead of the pdf icon.
Visible here:
http://localhost:3000/derek/view-templates/resource-center/refresh/resource-center
> feat(derek): add webinar card

- styleguide/derek/view-templates/leadership/_leadership.scss
Review Link: http://rsweb-9647-leadership-alignment.zoolander.dev.website.rackspace.com/about/leadership
> RSWEB-9647: fix mobile alignment

- .eslintrc.js
- karma.conf.js
- styleguide/_layouts/default.jade
- styleguide/_themes/derek/scss/snowflakes/homepage.scss
- styleguide/_themes/global/scss/buttons.scss
- styleguide/derek/incubation/_data.json
- styleguide/derek/incubation/homepage-de.ejs
- styleguide/derek/incubation/homepage-es.ejs
- styleguide/derek/incubation/homepage-pt.ejs
- styleguide/derek/pattern-components/headers/_headers.scss
- styleguide/derek/pattern-components/headers/header-refresh-homepage.ejs
- styleguide/derek/pattern-components/headers/header-refresh.ejs
- styleguide/derek/pattern-components/headers/headers.js
- styleguide/derek/pattern-components/headers/headers.spec.js
- styleguide/derek/pattern-components/platforms/_platforms.scss
This is an embedded-SVG solution for the homepage and interior banners, and also resolves other minor cosmetic issues with the homepage.
> RSWEB-9810: Fix Banners and Cleanup Homepage

- styleguide/derek/pattern-components/awards/_awards.scss
http://rsweb-9816-why-rackspace-awards.zoolander.dev.website.rackspace.com/why-rackspace
> RSWEB-9816: fix mobile alignment for awards

- styleguide/derek/pattern-components/tabs/_tabs.scss
http://rsweb-9725-tab-wrap-alignment.zoolander.dev.website.rackspace.com/es-mx
> RSWEB-9725: update tab alignment for overflow

- styleguide/derek/view-templates/resource-center/_resource-center.scss
http://rsweb-9339-resource-image.zoolander.dev.website.rackspace.com/resources/whom-can-you-depend
> RSWEB-9339: resource image size in tablet viewports

- styleguide/_themes/global/scss/forms.scss
http://rsweb-9750-tabs-horizontal-scroll.zoolander.dev.website.rackspace.com
> RSWEB-9750: remove tab horizontal scroll

- styleguide/_themes/global/scss/rsweb-font-style.scss
This PR bumps rswebfont version.
> chore(rswebfont): Bump to 1.0.1

- styleguide/derek/pattern-components/resourceCenter-resource/refresh/_resourceCenter-resource.scss
This PR fixes background positioning and sizing.
> RSWEB-9648: Fix teaser background position and size

- styleguide/derek/pattern-components/quotes/_quotes.scss
widening quotes on rivers
local link
http://localhost:3000/derek/patterns/patterns
> style(derek): RSWEB-9853 - changed max-width on quote wrappers

- styleguide/derek/pattern-components/resourceCenter-resource/refresh/_resourceCenter-resource.scss
For review:
http://rsweb-10001-full-anchor-span.zoolander.dev.website.rackspace.com/resources
> RSWEB-10001: Anchor should be full height of resource

- styleguide/derek/global-components/mainnav/_mainnav.scss
- styleguide/derek/global-components/mainnav/mainnav.js
http://rsweb-9751-mobilenav-x.styleguide.dev.website.rackspace.com/derek/incubation/homepage
> RSWEB-9751 feat(nav x icon): nav x icon now toggles on mobile

- styleguide/derek/pattern-components/resourceCenter-resource/refresh/_resourceCenter-resource.scss
URL to test:
http://rsweb-10117-mini-resource-teasers.zoolander.dev.website.rackspace.com/solutions/migrate-to-the-cloud
Original issue:
https://www.rackspace.com/solutions/migrate-to-the-cloud
> RSWEB-10117: Fix hover text decoration

- styleguide/derek/global-components/mainnav/_mainnav.scss
> fix(logo): fix logo from borked ff mobile view

- styleguide/derek/pattern-components/headers/_headers.scss
http://rsweb-9536-interior-banner.www.dev.website.rackspace.com/managed-hosting
http://rsweb-9536-interior-banner.www.dev.website.rackspace.com/events
http://rsweb-9536-interior-banner.www.dev.website.rackspace.com/customer-stories/mundo-joven
http://rsweb-9536-interior-banner.www.dev.website.rackspace.com/about/leadership/joe-eazor
> RSWEB-9865: internal mobile height

- styleguide/derek/pattern-components/headers/headers.js
https://jira.rax.io/browse/MTE-1958
> fix(banners): Resolve non-wrap for banner

- styleguide/_themes/derek/scss/patterns/panels.scss
This PR resolves an alignment issue with leads inside of panels
> MTE-2222: Alignment inside panels

- styleguide/derek/global-components/modal/_modal.scss
https://jira.rax.io/browse/MTE-2209
> fix(modal): rule is getting replaced by jqui

- styleguide/derek/pattern-components/headers/_headers.scss
- styleguide/derek/pattern-components/headers/header-refresh.ejs
style(derek): interior banner shorten and quick remove angles.
> mte-2310-interior-banners

- styleguide/derek/view-templates/stories/_stories.scss
Update banner for example page: /customer-stories/mckesson
> refactor(banner): Update customer story banner

- styleguide/derek/global-components/tracking/tracking.js
- styleguide/derek/global-components/tracking/tracking.spec.js
> feat(data): Add tracking class for GCP login.

- styleguide/derek/pattern-components/headers/_headers.scss
> fix(banners) - hiding background image on mobile

- styleguide/_themes/global/scss/swatch.scss
@brantdarilek these are the new swatches
> feat(swatches): adding havas colors to swatch file

- styleguide/_themes/derek/scss/_main.scss
- styleguide/derek/incubation/homepage.ejs
- styleguide/derek/pattern-components/about-river/_about-river.scss
- styleguide/derek/pattern-components/about-river/about-river.ejs
_Preview:_
http://mte-3366-about.styleguide.dev.website.rackspace.com
http://mte-3366-about.zoolander.dev.website.rackspace.com
> MTE-3366: About river

- styleguide/derek/global-components/modal/_modal.scss
- styleguide/derek/global-components/social/_social.scss
- styleguide/derek/incubation/homepage.ejs
- styleguide/derek/pattern-components/industry-river/_industry-river.scss
Just a cleanup PR to get rid of home page tabs and fix lint issues
> chore(homepage): remove tabs

- styleguide/derek/pattern-components/page-banner/_page-banner.scss
This PR sets the correct banner path so it works on the Drupal-side as well.
> fix(homepage): Correct banner path

- styleguide/derek/global-components/subnav/_subnav.scss
Update subnav background and active/hover state per ticket.
> feat(subnav): Update the background color and hover state.

- styleguide/_themes/global/scss/buttons.scss
- styleguide/derek/global-components/filter-bar/_filter-bar.scss
- styleguide/derek/pattern-components/ias/_ias.scss
- styleguide/derek/pattern-components/key-offers/_key-offers.scss
- styleguide/derek/pattern-components/o365-table/_o365-table.scss
- styleguide/derek/pattern-components/quotes/_quotes.scss
- styleguide/derek/pattern-components/tabs/_tabs.scss
- styleguide/derek/pattern-components/value-props/_value-prop.scss
- styleguide/derek/view-templates/stories/_stories.scss
This updates the following patterns to use havas text and colors:
Quotes
-----------------------------------------------------
Quote (Customer Story Content type)
Quote (Customer Story quote build mode)
Quote content type
3 color quotes
Tab titles
-----------------------------------------------------
CTAs
-----------------------------------------------------
Lead
Learning
Leaving (login page)
o365 cta's = up for debate
Announcement
-----------------------------------------------------
Value Prop (Card)
-----------------------------------------------------
Feature (Card)
-----------------------------------------------------
IAS (Card)
-----------------------------------------------------
Key Offers (Card)
-----------------------------------------------------
> feat(styles): updating numerous card patterns for havas colors and text

- styleguide/derek/pattern-components/lp-callout/_lp-callout.scss
This PR fixes the landing page call out z-index value.
> MTE-3477: Fix the landing page callout z-index

- styleguide/derek/incubation/homepage.ejs
- styleguide/derek/pattern-components/page-banner/_page-banner.scss
> chore(homepage): Slight animation tweak

- styleguide/derek/pattern-components/page-banner/_page-banner.scss
Minor tweak to fix the side scrolling issue on the homepage in mobile.
> fix(banner): Resolve side-scrolling issue on mobile

- styleguide/derek/global-components/basement/_basement.scss
- styleguide/derek/global-components/basement/basement.ejs
Mimicking the behavior in the refresh branch from [here](https://github.com/rackerlabs/zoolander/pull/583/files#diff-5a37d715f2c6d1917b9104c687a6334cR10) in the master branch.  This minimizes the changes needed down the road.
> MTE-3537: Add rsBasement to legacy branch

- styleguide/_themes/global/scss/forms.scss
> feat(style): color change for lp form

- styleguide/derek/pattern-components/headers/header-refresh-2019.ejs
- styleguide/derek/pattern-components/headers/headers.js
Testing basic animations for other page banners
> feat(animations): adding basic header animations to interior banners

- dist/derek/view-templates/events/events-interior.html
- styleguide/derek/view-templates/events/_events.scss
- styleguide/derek/view-templates/events/events-interior.ejs
https://jira.rax.io/browse/MTE-1503
> MTE-1503: Adds a Languages Spoken for Event content.

- styleguide/derek/pattern-components/industry-river/_industry-river.scss
- styleguide/derek/pattern-components/industry-river/industry-river.ejs
This fixes the breaking of the grid when text is too long.
> fix(grid): industry river grid fix for long text

- styleguide/derek/pattern-components/page-banner/_page-banner.scss
https://jira.rax.io/browse/MTE-3911
Add special classed for the specific image links. 
*note* the the ES and PT image appear to be the same link.. but in the event that changes.. I created a separate class.
> MTE-3911: Optimize APAC, Spanish, Portuguese banners on mobile

- styleguide/derek/global-components/mainnav/_mainnav.scss
Adjusts the medium font-size so that the navbar and search icon align on the medium breakpoint.
https://jira.rax.io/browse/MTE-3912
> MTE-3912: Spanish Navigation issue with tablet size.

- styleguide/_themes/global/scss/forms.scss
- styleguide/derek/view-templates/events/_data.json
- styleguide/derek/view-templates/events/_events.scss
- styleguide/derek/view-templates/events/_partials/form.ejs
- styleguide/derek/view-templates/events/_partials/marketo-form.ejs
- styleguide/derek/view-templates/events/events-interior-marketo.ejs
This PR adds new sass overrides for the injected Marketo forms.
> feat(styling): new overrides for marketo forms

- styleguide/_themes/derek/scss/_main.scss
- styleguide/_themes/global/scss/bootstrap_variables.scss
- styleguide/derek/pattern-components/ribbon/_partials/ribbon.ejs
- styleguide/derek/pattern-components/ribbon/_ribbon.scss
- styleguide/derek/pattern-components/ribbon/ribbon.ejs
- styleguide/derek/patterns/patterns.ejs
https://jira.rax.io/browse/MTE-4091
Note:
I kind of went all rogue since I'm not familiar with the naming and other conventions used.. I'm prepared to rename things and move things around... 
model for blue strip thingy:
Note: I added a stupid link so I could share the location of the pattern .. I'll remove it if necessary..
http://mte-4091-make-blue-strip.styleguide.dev.website.rackspace.com/derek/patterns/patterns#ribbon
> MTE-4091: Make blue strip thingy for webinar

- styleguide/derek/global-components/mainnav/_mainnav.scss
- styleguide/derek/pattern-components/about-river/_about-river.scss
- styleguide/derek/view-templates/resource-center/_resource-center.scss
This PR just fixes a few sass-linting issues.
> Fix sass lint issues 

- styleguide/derek/templates/index.jade
- styleguide/derek/templates/landing-page-noBanner/_data.json
- styleguide/derek/templates/landing-page-noBanner/_layout.jade
- styleguide/derek/templates/landing-page-noBanner/landingpage-single-webinar.ejs
- styleguide/derek/templates/landing-page/_data.json
This PR adds a new lp layout for the single webinar. It's reusing some of the events pattern for the form columns and moderators.
> feat(page): new single webinar landing page

- styleguide/derek/view-templates/events/_events.scss
https://jira.rax.io/browse/MTE-4018
> MTE-4018: Making the US Hosted Events event form and details align.

- styleguide/derek/global-components/tracking/tracking.js
- styleguide/derek/global-components/tracking/tracking.spec.js
This PR resolves an issue with the CTA tracking when multiple CTAs are present on a single page
> MTE-4358: Resolves issue with multi-CTA tracking

- styleguide/derek/global-components/tracking/tracking.js
- styleguide/derek/global-components/tracking/tracking.spec.js
This PR fixes CTA tracking when occuring inside a modal.
> MTE-4360: Allows CTA tracking to occur in modal

- styleguide/derek/global-components/modal/_buy-now.scss
- styleguide/derek/pattern-components/page-banner/page-banner.ejs
This PR resolves some IE11/Edge issues
Here's a screenshot of IE11 in browserstack w/ this fix:
This was what it looked like before:
> MTE-4368: Resolve IE11/Edge issues

- styleguide/derek/pattern-components/video/_video-embed.scss
- styleguide/derek/pattern-components/video/ondemand-video.ejs
- styleguide/derek/templates/landing-page-noBanner/landingpage-ondemand-webinar.ejs
Adding some buffer room around embedded videos and on on-demand lp's
> style(video): fixing ondemand video page margins

- karma.conf.js
- npm-shrinkwrap.json
- package.json
- styleguide/derek/global-components/tracking/tracking.spec.js
This PR resolves the travis test failures.
Changes made:
1. Made a slight modification to `tracking.spec.js` which was the actual culprit.  The form submission was causing a page reload, so I force the submit action to return false now instead so it will only listen to javascript events. 
2. Installed and configured the `karma-verbose-reporter` package to provide a little bit more visual feedback into the test pass/failures
> fix(travis): Resolve test failure

- styleguide/derek/pattern-components/webinar-item/_partials/webinar-item.ejs
- styleguide/derek/pattern-components/webinar-item/_webinar-item.scss
https://jira.rax.io/browse/MTE-4520
Updates styling to allow for rubbish way Drupal shoves paragraph tags around everything.
> MTE-4520: Webinar Series Bugs

- styleguide/derek/global-components/modal/_modal.scss
https://jira.rax.io/browse/MTE-4678
This change adds style to the loader thing for the webform modal.
> MTE-4678: Move webform modals over to using our custom solution

- scripts/build-pages.sh
This PR fixes a minor issue with the gh-pages script
> fix(scripts): Fix gh-pages script

- styleguide/derek/global-components/tracking/tracking.js
- styleguide/derek/global-components/tracking/tracking.spec.js
This PR ensures CTA tracking is enabled for submit buttons.
> MTE-4883: Ensure CTA tracking works for submit buttons

- styleguide/derek/pattern-components/cust-story-river/_cust-story-river.scss
- styleguide/derek/pattern-components/page-banner/_page-banner.scss
This PR should resolve the duplicate banner issue on the homepage for browsers wider than 992px
Left side is production, right side is my branch:
> MTE-4907: Resolve duplicate banner load issue

- styleguide/derek/templates/thought-leadership-overview/_partials/_nav.scss
- styleguide/derek/templates/thought-leadership-overview/_thought-leadership.scss
- styleguide/derek/templates/thought-leadership-overview/article.ejs
This PR changes banners from inline css to `<picture>` tags to allow for use of responsive images inside drupal.
> chore(solve): Switch banners to <picture> tags

- styleguide/derek/templates/thought-leadership-overview/_thought-leadership.scss
- styleguide/derek/templates/thought-leadership-overview/article.ejs
https://jira.rax.io/browse/MTE-5049
I tried to make the quote look like the attachment in the ticket.
Also I completely removed the attribution info, or rather the way I understood it the part that indicates whom the quote is from...
I changed the quote characters.
I shortened the red dividers to match the image in the ticket
> feat(quote): Change quote to live in blockquote element.

- package.json
- styleguide/derek/templates/thought-leadership-overview/_thought-leadership.scss
https://jira.rax.io/browse/MTE-5153
> MTE-5153: Fix IE issues for CSS grid

- styleguide/derek/templates/thought-leadership-overview/_partials/cta-callout.ejs
- styleguide/derek/templates/thought-leadership-overview/_thought-leadership.scss
JIRA: https://jira.rax.io/browse/MTE-5182
This PR adds CTA callout functionality to the solve articles
> MTE-5182: Add CTA callout

- styleguide/derek/templates/thought-leadership-overview/_thought-leadership.scss
This PR fixes a bug with the focus state on solve links.
> MTE-5238: Remove underline on focus state

- styleguide/derek/templates/thought-leadership-overview/_thought-leadership.scss
- styleguide/derek/templates/thought-leadership-overview/article.ejs
This PR is for some design cleanup per a discussion with the designers earlier (see ticket for details)
> MTE-5241: Design cleanup

- styleguide/derek/templates/thought-leadership-overview/_partials/related-topics.ejs
- styleguide/derek/templates/thought-leadership-overview/_thought-leadership.scss
JIRA: https://jira.rax.io/browse/MTE-5244
Relates to: rackerlabs/solve#19
This PR makes only certain things clickable.
> MTE-5244: Make only certain things linkable

- styleguide/derek/templates/thought-leadership-overview/_partials/_nav.scss
- styleguide/derek/templates/thought-leadership-overview/_thought-leadership.scss
JIRA: https://jira.rax.io/browse/MTE-5239
This PR attempts to resolve weird z-index issues with Drupal
> MTE-5239: Resolve z-index issues

- styleguide/derek/templates/thought-leadership-overview/_thought-leadership.scss
JIRA: https://jira.rax.io/browse/MTE-5245
This PR sets a max container of 970px on the content portions of the article.
> MTE-5245: Set max-width on content container

- styleguide/derek/templates/thought-leadership-overview/_partials/_nav.scss
- styleguide/derek/templates/thought-leadership-overview/solve-nav.js
JIRA: https://jira.rax.io/browse/MTE-5260
This PR makes the sponsor logo optional. There is a www PR to follow as well.
> MTE-5260: Make sponsor logo optional
