rackerlabs/zoolander

Gruntfile.js
grunt/build.js

* Running `grunt build` will run build scripts for all themes. Previously, it defaulted to `global`. 
* Added new `all` parameter to build task. `grunt build:all`

chore(build): update grunt build to build all themes

---

Gruntfile.js
docs/_layouts/default.html
docs/derek/components/navigation.html
docs/derek/index.md
grunt/watch.js
themes/derek/scss/components/navigation.scss

These changes were based on rackspace.com
* Multiple variations for ceiling navigation. 
* Defaults to hidden in small viewports (This needs to improved to allow for responsive versions)
**Note** This PR does not try to reproduce the styles exactly as it exists today. #10 will need to be completed before styling is addressed
**Ceiling with buttons**
**Ceiling with labels and links**
**Drop Down when in navbar-left**
**Drop Down when in navbar-right**

Add ceiling navigation

---

README.md
bower.json
docs/.gitignore
package.json

This PR adds a few convenience `npm` commands and leverages local installs for `grunt` and `bower`.

refactor(npm): expand on install, build and server tasks

---

package.json

Adds a harp:compile option to package.json to allow for zoolander compilation, with out adding to git repo.

chore(package.json): Add "harp:compile" script

---

styleguide/_themes/derek/scss/components/_basement.scss

PR #149 introduced a bug in the basement that I missed the first time around. 
Otherwise the basement flags won't show up.

RSWEB-6655: Fix basement flag bug

---

styleguide/_themes/derek/scss/components/mainnav.scss
styleguide/derek/_partials/_mainnav.ejs

This PR converts the tertiary triggers to `<span>` tags from `<a>` tags.  This was done in #163 for top-level nav, but got overlooked in the tertiary triggers.

RSWEB-6329: Convert tertiary menu triggers from anchors to spans.

---

styleguide/_themes/derek/scss/components/mainnav.scss

This PR removes the border top from the search bar, and moves the search carrot over on sm, md & lg view ports.

RSWEB-6329: Minor tweaks to the nav search

---

styleguide/_themes/derek/scss/snowflakes/events.scss
styleguide/derek/examples/events-interior.ejs

Jira: https://jira.rax.io/browse/RSWEB-6688
This PR is a follow up to #199.  As I did some initial testing in www, based on the way the JS was setup, it turns out we do need a predefined canvas size for the map after all.

RSWEB-6688: Map canvas does need predefined dimensions after all

---

styleguide/_themes/derek/scss/patterns/lead.scss
styleguide/_themes/global/scss/banners.scss
styleguide/_themes/global/scss/fonts.scss
styleguide/_themes/global/scss/global.scss
styleguide/derek/_partials/solutions/header-large.ejs
styleguide/derek/_partials/solutions/header-largeIMAC.ejs
styleguide/derek/_partials/solutions/header-medium.ejs
styleguide/derek/_partials/solutions/lead.ejs
styleguide/derek/_partials/typography/heading.ejs
styleguide/derek/assets/_layout.jade
styleguide/derek/assets/photography.jade

https://jira.rax.io/browse/RSWEB-6940
Switches h1 to lead position and h2 to banner position. Need to switch h2 class for our drupal pattern banners to banner-headline, to avoid the h2 resizing issue, since h2 is our designated river title size.
View title in banner cases here:
http://localhost:9000/derek/assets/photography
typography cases here: 
http://localhost:9000/derek/assets/typography
and the lead/heading changes here:
http://localhost:9000/derek/examples/solutions

style(zoolander):h1-swap

---

styleguide/_themes/derek/scss/patterns/grid/businessResource.scss

Updates resource class to ```display: flex;``` so that background will extend full height of the row.

RSWEB-7241: equal height fix to resource class

---

styleguide/_themes/derek/scss/globalElements/footer.scss
styleguide/_themes/global/scss/bootstrap_overrides.scss

Changes the focus state to be the original link color and removes the underline. Also removes the change to black for the active state in the footer.
Can be seen here http://localhost:9000/derek/examples/events

RSWEB-7205: focus state color should not change in footer links

---

styleguide/_themes/derek/scss/globalElements/mainnav.scss

Removes ```border-bottom: 1px solid #333; ``` from the ```navbar-container``` class for screen @ max-width: 991px.
Navigate to http://localhost:9000/derek/examples/section-overview in zoolander and set screen to width between 768px and 991px. The border lines should not appear when the Search is expanded.

RSWEB-7209: remove border bottom in tablet

---

styleguide/_themes/derek/scss/globalElements/mainnav.scss
styleguide/_themes/global/scss/bootstrap_overrides.scss
styleguide/derek/_partials/_mainnav.ejs
styleguide/js/zoolander.js

Things Done:
1.) Added down carots to desktop dropdown buttons, and right carots to mobile.
2.) Added toggle functionality for arrows on mobile when open/close 
3.) Added subtle bottom border to drop down links in mobile for differentiation purposes.
4.) Set a larger font size to all nav links in mobile.
I also switched our drop down trigger to 'clicks' instead of 'hovering' for a more consistent UX. This may still be up for debate. This also helps in developing for mobile/desktop as right now we're competing against the different listeners.

RSWEB-7046: multiple global nav improvements

---

styleguide/_themes/derek/scss/globalElements/mainnav.scss

Reduced padding on nav items so the nav doesn't break

bug(nav): reduced padding for translations in nav

---

styleguide/_themes/derek/scss/patterns/announcements.scss
styleguide/_themes/derek/scss/patterns/subpanels.scss
styleguide/derek/_partials/solutions/announcements.ejs
styleguide/derek/examples/solutions.ejs
styleguide/derek/examples/subpanels.ejs

This PR makes the following changes to the announcement pattern, in preparation for being integrated into www: 
1. Renamed `announcement-container` to `announcement-wrapper` to avoid confusion with bootstrap containers.
2. Removed left/right padding
3. Since we have to use FontAwesome until new icons are ready, I made a few updates to the icon class. 
4. Renamed announcent type classes, to be more indicative of what they actually are supposed to be.
5. Set subpanels version of announcement to mimic mobile experience.
6. Setup type-specific icons.
7. Pull all non-essential code out of the announcement partial

RSWEB-7033: Adjust announcements for www-readiness.

---

styleguide/_themes/global/scss/banners.scss

Updates min banner height for mobile to avoid long banner text being cut off or the banner background showing below the subnav.
- example page: https://www.rackspace.com/managed-aws
- Corresponding www PR with margin top being removed. (1276)

RSWEB-7235: update mobile banner min height

---

styleguide/_themes/global/scss/banners.scss

This PR fixes a padding issue on imac banners caused by removal of a margin last week.

RSWEB-7381: Adds additional padding to top to account for fixed nav

---

styleguide/_layouts/default.jade
styleguide/css/main.scss
styleguide/derek/examples/index.jade
styleguide/derek/examples/landing-page/_layout.jade
styleguide/derek/examples/landing-page/index.jade
styleguide/js/zoolander.js

@amberRrucker @WidgetsBurritos Can I get code/design review:
- Brought back the slide toggle ability for better previewing landing pages. 
- Made the navbar scrollable incase all are collapsed/or if we add more links.
- Fixed a bug that double injects content on some pages (ex: /derek/examples/landing-page/) thus  causing nav click events to run twice. 
- Added proper tables link

RSWEB-7348: bug(zoolanderNav): brought back nav slide toggle

---

styleguide/_themes/global/scss/tables.scss
styleguide/derek/examples/tables.ejs
styleguide/js/zoolander.js

Moved over our old tables into a new maintainable pattern.
Desktop
Mobile

RSWEB-7110: Added basic compare tables pattern

---

styleguide/_themes/global/scss/banners.scss

RSWEB-7397
Reducing button padding for imac banner button ONLY to 8px top/bottom
Visible here:
http://localhost:9000/derek/examples/imac

RSWEB-7397: imac-banner-button-padding-only

---

styleguide/_themes/global/scss/fonts.scss

RSWEB-7350
style(zoolander):headline font switch
Switching our headline (h1-h3) font to Khand and adjusting for font weight.
Will has taken a look and approved. Should be previewed on this page: 
http://localhost:9000/derek/examples/solutions-usage to see how it interacts with out patterns
here:
http://localhost:9000/derek/examples/homepage to see how it interacts on the homepage
and then here: 
http://localhost:9000/derek/assets/typography to see it with other typographic examples
Should have code review, design review, review from @ejchiefs then put on staging for the ECMs to review.

rsweb-7350-headline-font-change

---

styleguide/_themes/global/scss/tables.scss

bug(zoolander):table font size overridden by www
Can be viewed here (but should be the same):
http://localhost:9000/derek/examples/tables
Fixes issues here: 
https://admin.rackspace.com/node/5725

rsweb-7420-table-fontsize

---

styleguide/_themes/global/scss/banners.scss
styleguide/derek/examples/landing-page/cta-LP.ejs
styleguide/derek/examples/landing-page/form-LP.ejs
styleguide/derek/examples/landing-page/video-LP.ejs

RSWEB-7435
bug(zoolander):imac banner padding issues
Adjusting imac banner padding and top margins to not be covered by main nav. Had to wrap landing page in a wrapper. DO NOT MERGE UNTIL LANDING PAGES ARE WRAPPED IN landingpage-wrapper
Fix can be seen here: 
http://localhost:9000/derek/examples/homepage
as well as here:
http://localhost:9000/derek/examples/landing-page/cta-LP

RSWEB-7435: imac-banner-padding

---

styleguide/_layouts/default.jade
styleguide/_themes/global/scss/bootstrap_variables.scss
styleguide/_themes/global/scss/fonts.scss
styleguide/derek/assets/typography.jade

RSWEB-7441
style(zoolander):subhead font switch
Can be viewed on homepage and solutions examples page to check for any weirdness.

rsweb-7441-subhead-switch

---

styleguide/_themes/derek/scss/snowflakes/stories.scss
styleguide/derek/examples/stories-interior.ejs

This PR removes the image and adds a logo to the imac banner on stories and swaps the company bio/outcome statements.

RSWEB-7338: Add logo to banner, swap company bio/outcome

---

styleguide/_themes/derek/scss/components/subnav.scss
styleguide/_themes/derek/scss/globalElements/mainnav.scss

Increased the font size on drop down links in global nav and increased font weight/size on sub navs to match global nav

RSWEB-7179: style(nav): increase font size for links

---

styleguide/_themes/derek/scss/globalElements/mainnav.scss
styleguide/_themes/global/scss/banners.scss

This PR kills the `margin-top` on the imac and events banners.  This is tied to killing the page wrap and www and must go out with that PR.

RSWEB-7323: Kill page wrap

---

styleguide/_themes/derek/scss/patterns/panels.scss
styleguide/_themes/global/scss/vendor_prefixes.scss

Sets `.panel-flex` to stack vertically.
This closes alternate PR https://github.com/rackerlabs/zoolander/pull/279.

RSWEB-7468: panel flex mixin for stacked content

---

styleguide/_themes/derek/scss/patterns/cards/businessResource.scss
styleguide/_themes/derek/scss/patterns/panels.scss

First commit - Fixes flex widths not spanning 100%. 
Second commit - Adds maintainable "push" classes for panel-flex, that use `margin-left` instead of `left`.

RSWEB-7287: QE Bugfixes

---

styleguide/_themes/derek/scss/snowflakes/stories.scss
styleguide/_themes/global/scss/vendor_prefixes.scss
styleguide/derek/examples/stories-interior.ejs
styleguide/derek/examples/stories.ejs

The previous version of the stories overview page only allowed for image-based logos, but we're not going to have logos for everything, so we need a text fail-over option. Due to vertical-alignment concerns, it required a bit of refactoring, and I opted to use the `<img>` tag instead of background images. 
http://localhost:9000/derek/examples/stories

RSWEB-7341: Allow for text in addition to logos

---

styleguide/_themes/derek/scss/snowflakes/homepage.scss

This PR removed the the solutions declaration that allows us to remove all inline style blocks from the home page.

refactor(rsweb-7637-remove-hp-inline-styles): remove solutions class

---

package.json
styleguide/_themes/derek/scss/globalElements/ceilingLp.scss
styleguide/_themes/derek/scss/patterns/cards/businessResource.scss
styleguide/_themes/derek/scss/patterns/cards/modules.scss
styleguide/_themes/global/scss/forms.scss
styleguide/_themes/global/scss/swatch.scss

This PR removes color functions from properties and creates a black-shadow variable to be used globally for elements that contain drop shadows.

chore(rsweb-7086-sass-lint-color-literals): remove color functions

---

styleguide/_themes/derek/scss/_main.scss
styleguide/_themes/derek/scss/patterns/image.scss

Adds `height: auto;` for image content type. 
Corresponding www PR - https://github.rackspace.com/rswebteam/www/pull/1363

RSWEB-7625: add height auto to image content type

---

styleguide/derek/examples/events-interior.ejs
styleguide/derek/examples/events.ejs
styleguide/derek/examples/homepage.ejs
styleguide/derek/examples/office365.ejs
styleguide/derek/examples/section-overview.ejs
styleguide/derek/examples/swatches.ejs

Adds ```<div class="contentOffset">``` to example pages on zoolander to account for navigation height at top of page. 
*DOES NOT AFFECT www
ex: 
http://localhost:9000/derek/examples/events-interior
http://localhost:9000/derek/examples/events
http://localhost:9000/derek/examples/homepage
http://localhost:9000/derek/examples/office365
http://localhost:9000/derek/examples/section-overview
http://localhost:9000/derek/examples/swatches

RSWEB-7648: add contentOffset to example pages

---

styleguide/_themes/derek/scss/globalElements/mainnav.scss
styleguide/_themes/global/scss/buttons.scss
styleguide/derek/_partials/solutions/cta-bottom.ejs
styleguide/derek/_partials/solutions/cta.ejs
styleguide/derek/assets/buttons.jade

RSWEB-7349
style(cta):removing 100% cta width
Removing 100% width as well as refactoring and adjusting design for cta pattern
Changes can be seen/tested on 
http://localhost:9000/derek/assets/buttons
http://localhost:9000/derek/examples/solutions and
http://localhost:9000/derek/examples/homepage
Looking to make sure this won't break buttons in production either. Should try and put on staging for full visual testing.

rsweb-7349-cta-refactor-and-width-change

---

styleguide/_themes/derek/scss/globalElements/basement.scss
styleguide/_themes/global/scss/bootstrap_variables.scss
styleguide/derek/_partials/_rug.ejs

We need to set are largest breakpoint from 1200 to 1280 if that's actually are max width. This prevents side scrolling issues related to the breakpoint.  
Additionally since `.rug-container` sets the left and right margins to zero, we can't use the `.row` class in here.  I'm creating a www PR for this fix as well. 
And also, the basement padding should be set to match the gutter width.

RSWEB-7825: [1280] Change breakpoint from 1200 to 1280

---

styleguide/_themes/derek/scss/globalElements/basement.scss

Added padding to basement to vertically center align text

RSWEB-7732 Padding for basement

---

styleguide/_themes/derek/scss/patterns/panels.scss

RSWEB-7703: Fix lead text alignment in mini panels

---

styleguide/_themes/global/scss/banners.scss
styleguide/_themes/global/scss/fonts.scss

This PR converts headings to title case by removing the text-transform attribute from the headings mixin and adding it to the imacBanner-heading to ensure we retained uppercase for our banners.

style(rsweb-7848-title-case): remove uppercase from headings

---

package.json
styleguide/_themes/derek/scss/snowflakes/homepage.scss
styleguide/_themes/derek/scss/snowflakes/o365.scss
styleguide/_themes/global/scss/fonts.scss

This PR addresses `warning  Nesting depth 3 greater than max of 2  nesting-depth` sass lint errors on the following files.  Here is how I did it. A few assumptions were made so this will need to be verified separately. 
- homepage.scss: I just removed all of the old style code as its no longer used. @amberRrucker is this correct? 
- o365.scss: By forcing `td` to be a direct child of `tr`, it removes a level of nesting from sass-lint's perspective.
- fonts.scss: By forcing `li` to be a direct child of `.green` or `.teal` lists, it removes a level of nesting from sass-lint's perspective.
An important thing to note is that I left the nesting issues on the `tabs.scss` file. The reason for this is that the tabs are getting refactored next couple of sprints, so we can just let that process …

RSWEB-7085: Sass-lint nesting issues

---

styleguide/derek/_partials/_ceiling.ejs

This PR removes the developer and partner links from the ceiling. This work technically only needs to be done on www, but I did it here as well for consistency.

RSWEB-7996: Remove partner/developer links

---

styleguide/_themes/derek/scss/patterns/cards/productFeatures.scss
styleguide/derek/_partials/cards/product-feature.ejs
styleguide/derek/layouts/features.ejs
styleguide/derek/solutions/solutions.ejs

This PR fixes a few layout issues with features:
1.) Adds `width: 100%;` to the pattern wrapper.
2.) Remove the `<div class="row row-eq-height">` from inside the pattern. This has to be done on the `www` side as well. 
3.) Removed the margin-bottom from the features pattern, as all margins/patterns between panes is now handled by the layouts instead of the pattern itself.
4.) Added `subpanel` and `subpanel-inner` classes to get zoolander markup to match up with www.
5.) Added the features pattern to the solutions page as it was missing. 
Note: Because this is just a bug fix, I stopped short of actually refactoring features, which I believe is in queue to be tackled in the not-too-distant future. For that reason, I did the minimal I deemed necessary to make zoolander useful for the …

RSWEB-7811: Remove row and adjust width for features

---

styleguide/_themes/derek/scss/patterns/cards/resources.scss

Sets min height for Additional Resources pattern to be at least 2 lines tall. 
http://localhost:9000/derek/solutions/solutions
`.additional-resource .row-eq-height { min-height: 78px; }`

RSWEB-7921: min height for row to be at least two lines

---

styleguide/_themes/derek/scss/globalElements/mainnav.scss

This PR sets the `font-size` to "0" for `.navbar-phoneicon` to hide inner text used by Infinity call tracking "autodiscovery". The phone number text has to be put in the element given class `.navbar-phoneicon` for autodiscovery to work but on mobile only the icon should be visible.

RSWEB-8009 [www] Infinity Numbers not displayed when the website is viewed on mobile

---

styleguide/_themes/derek/scss/snowflakes/homepage.scss

I've optimized both the png and jpg on the cdn but this should help a bunch.

RSWEB-8078: update homepage to use quadrant.jpg instead of quadrant.png

---

styleguide/_themes/derek/scss/snowflakes/stories.scss

Sets a max-height for the logos on the customer stories page

RSWEB-8083: max height for logo

---

package.json

This PR defines the files that should be preserved in within `node_modules/zoolander` when Zoolander is installed with NPM. The `dist` directory is ignored by default so installing it via NPM skips that directory.

feat(npm): add files to package.json

---

styleguide/_themes/derek/scss/snowflakes/homepage.scss

This PR pulls in a few minor style updates that are currently set inside `<style></style>` tags in a general content type. 
@amberRrucker can you please confirm this is the correct solution to this problem, instead of just removing the on page style altogether?

RSWEB-8405: Move CSS from general content type into repo

---

styleguide/derek/_partials/cards/list.ejs
styleguide/derek/_partials/typography/lists.ejs
styleguide/derek/assets/typography.jade
styleguide/derek/layouts/lists.ejs
styleguide/derek/solutions/solutions-usage.ejs

Adding documentation for bullets and removing old examples from zoolander.
Visible here: 
http://localhost:9000/derek/solutions/solutions-usage
and
http://localhost:9000/derek/assets/typography

RSWEB 8252 Bullet Documentation

---

styleguide/_themes/derek/scss/components/subnav.scss
styleguide/_themes/global/scss/modifiers.scss

This PR fixes a few gutter related issues.  
1. d54c7941ae27c7cc1fd40764fedfe145637868e5 - Gets rid of containers around subnav and specifies a better gutter width for subnav items
2. 3a383650582df5bbd81de168ca0ab3908c92bf37 - Adjusts padding on half-padding/standard-padding when viewing in 1280px+
3. 068b4854d45d1bd6d22bec68044fd7f2796ce46d - Sets a margin-right of `$grid-gutter-width` unless you're in 1280px + gutter width*2. 
Can be tested in zoolander here: http://localhost:9000/derek/incubation/office365
One thing to keep in mind (and part of the reason for item 3 above, is to give room for the chat slider button.)

RSWEB-8096: Fixes gutter related issues.

---

styleguide/_themes/derek/scss/patterns/lead.scss
styleguide/_themes/derek/scss/patterns/panels.scss
styleguide/_themes/global/scss/buttons.scss
styleguide/_themes/global/scss/fonts.scss
styleguide/derek/_partials/solutions/lead.ejs

Refactors lead pattern.
- removes `.lead` class and uses `.lead-wrapper` so that there is no need to overwrite bootstrap class 
- structure is in alignment with CTA refactor and uses maintainable
- does not alter subnav elements that still use original `.lead` class
http://localhost:9000/derek/solutions/solutions-usage
http://localhost:9000/derek/solutions/subpanels

RSWEB-8026: refactor lead classses

---

styleguide/_themes/derek/scss/components/subnav.scss

Fixes the issue when viewing in the mobile viewport where the CTA in the subnav is off the screen on the left side.
http://localhost:9000/derek/incubation/office365

RSWEB-8507: fix for subnav mobile being cut off on left side

---

styleguide/_themes/derek/scss/components/tabs.scss
styleguide/derek/_partials/solutions/tabs-long.ejs
styleguide/derek/_partials/solutions/tabs-vertical.ejs
styleguide/derek/_partials/solutions/tabs-verticalLong.ejs
styleguide/derek/_partials/solutions/tabs.ejs
styleguide/derek/layouts/tabs.ejs
styleguide/derek/solutions/solutions-usage.ejs

I split this into two separate commits, which is probably the easiest way to view this: 
- bb2eec95193686e4cf51995d0f7b1a4b3763aac8: Just adds basic support for vertical tabs
- ac21bf17568e8499909364322680e86a0e8b68de:  Cleans up some redundancy by creating a separate horizontal tabs classes, which allows us to distinctly style horizontal vs vertical in the future if we need to.

RSWEB-8590: Vertical tabs

---

styleguide/_themes/global/scss/buttons.scss

RSWEB-8654
Adding back in the background to the learning button to avoid having a green background thats occurring on the /cloud page.

rsweb-8654-learning-bug

---

styleguide/_themes/derek/scss/components/subnav.scss

RSWEB-8624
Adjusting the subnav cta to have proper alignment
Also removed a transparent bottom border on the subnav that was causing a 1px gap below hover state on subnav menu items.
Viewable here:
http://localhost:9000/derek/incubation/office365

rsweb-8624-submenu-cta

---

styleguide/_themes/derek/scss/globalElements/mainnav.scss

Changes out Rackspace logo in eyebrow to remove blue-gray bg from svg. 
Resizes new svg and adds slight transition when going from desktop to mobile.
http://localhost:9000/derek/templates/section-overview

RSWEB-8623: change out logo image to rm bg color

---

styleguide/_themes/derek/scss/_main.scss
styleguide/_themes/derek/scss/patterns/cards/cornerPocket.scss
styleguide/derek/_partials/cards/corner-pocket.ejs
styleguide/derek/layouts/leadCornerPocket.ejs
styleguide/derek/solutions/solutions-usage.ejs
styleguide/derek/solutions/solutions.ejs
styleguide/derek/templates/landing-page/video-LP.ejs
styleguide/derek/templates/section-overview.ejs

RSWEB-8523
Addition of new corner pocket card. Included on solutions pages with documentation and added in the partial of leadSplit to account for the left aligned lead that we use in splits in www.

rsweb-8523-new-corner-pocket

---

styleguide/_themes/derek/scss/_main.scss
styleguide/_themes/derek/scss/components/tabs.scss
styleguide/_themes/derek/scss/patterns/portfolio.scss
styleguide/derek/_partials/solutions/portfolio.ejs
styleguide/derek/_partials/solutions/tabs-vertical.ejs
styleguide/derek/_partials/solutions/tabs-verticalLong.ejs
styleguide/derek/layouts/tabs.ejs

This PR adds the portfolio pattern into zoolander.
A few notes about this:
1. Mike asked me to not include the icon on the portfolio tabs, so it's just header/text/key offers now.
2. Since this is presently the only acceptable use of vertical tabs in the system, I replaced all existing vertical tab content with portfolio pattern content, instead of adding a new section for product portfolio. I think we covered it last time, but if I need to update any of the usage documentation around that, please let me know. 
3. Chatting with @runrog today, we opted to use gray backgrounds on all of the key offers here. The main issue with this is, without it the content would look oddly indented due to the padding on the key offer pattern. We could theoretically offset this padding with a margin, but …

RSWEB-8591: Add portfolio pattern

---

styleguide/_themes/derek/scss/patterns/announcements.scss
styleguide/_themes/derek/scss/patterns/cards/businessResource.scss
styleguide/_themes/derek/scss/patterns/cards/ias.scss
styleguide/_themes/derek/scss/patterns/cards/keyOffers.scss
styleguide/_themes/derek/scss/patterns/cards/modules.scss
styleguide/_themes/derek/scss/patterns/cards/productFeatures.scss
styleguide/_themes/derek/scss/patterns/lead.scss
styleguide/_themes/derek/scss/snowflakes/events.scss
styleguide/_themes/derek/scss/snowflakes/o365.scss
styleguide/_themes/global/scss/buttons.scss
styleguide/_themes/global/scss/cta.scss
styleguide/_themes/global/scss/fonts.scss
styleguide/derek/_partials/solutions/cta-bottom.ejs
styleguide/derek/_partials/solutions/lead.ejs
styleguide/derek/_partials/typography/body-copy.ejs
styleguide/derek/assets/typography.jade

RSWEB-8495
Adjusting links to be red and underlined in copy across the site.
Should darken on hover.

rsweb-8495-link-style

---

styleguide/_themes/derek/scss/patterns/cards/modules.scss
styleguide/derek/_partials/cards/list.ejs

RSWEB-7582
Fixing mobile list bug and adding list-wrapper to list pattern in zoolander (its already in www)
Visible on this page in zoolander:
http://localhost:9000/derek/solutions/solutions-usage
under the features section
Visible on these pages in www:
https://www.rackspace.com/email-hosting/webmail/features
https://www.rackspace.com/cloud/servers

rsweb-7582-list-bug-mobile

---

styleguide/_themes/derek/scss/components/subnav.scss
styleguide/_themes/derek/scss/patterns/announcements.scss
styleguide/_themes/derek/scss/patterns/panels.scss
styleguide/_themes/derek/scss/snowflakes/o365.scss
styleguide/_themes/derek/scss/snowflakes/swatches.scss
styleguide/_themes/global/scss/bootstrap_variables.scss
styleguide/_themes/global/scss/buttons.scss
styleguide/_themes/global/scss/forms.scss
styleguide/_themes/global/scss/modifiers.scss
styleguide/_themes/global/scss/swatch.scss
styleguide/_themes/global/scss/tables.scss
styleguide/derek/assets/swatches.ejs
styleguide/derek/incubation/office365.ejs

RSWEB-8494
This one took a bit of a weird turn. Instead of doing all of these individually I switched brand secondary and it effects these things:
corner-pocket text
subnav hover
learning button border
o365 discount triangle (isnt even used anymore. dumped the code for it.)
all a tags will switch to red and hover red(darken) to avoid them switching to mustard hover
Stakeholders need to see this on a dev branch pre deploy.

rsweb-8494-switch-brand-secondary

---

styleguide/_themes/global/scss/banners.scss
styleguide/derek/global-components/basement/_basement.scss
styleguide/derek/global-components/ceiling/_ceiling.scss
styleguide/derek/global-components/ceiling/_ceilingLp.scss
styleguide/derek/global-components/ceiling/ceiling.ejs
styleguide/derek/global-components/footer/_footer.scss
styleguide/derek/global-components/footer/footer.ejs
styleguide/derek/global-components/nav/_nav.scss
styleguide/derek/global-components/nav/nav.ejs
styleguide/derek/global-components/rug/_rug.scss
styleguide/derek/global-components/subnav/_subnav.scss
styleguide/derek/incubation/homepage.ejs
styleguide/derek/incubation/office365.ejs
styleguide/derek/templates/section-overview.ejs

RSWEB-8705 
Getting the gutters into some semblance of normal.
You may notice some additional padding on the rug, footer, basement and imac banner containers. In order to have those elements align with the beginning of the actual word of the links in the main navigation and subnav instead of the beginning of the padded link container (you can see this on those links hover states) those containers got some extra padding. The actual first word of those links also now match up with the left side of the page elements, which is why I didnt instead remove padding from the main nav and subnav. 
Should only need to remove the container declaration from the ceiling in www
This can best be seen on this page:
http://localhost:9000/derek/templates/section-overview

RSWEB-8705: consistent gutters

---

bs-config.js
package.json
styleguide/_layouts/default.jade

https://jira.rax.io/browse/RSWEB-8848
Change summary:
* Add browser sync
* Add script for starting browser sync
* Add browser sync snip for injecting updates
Instructions:
1. npm install
2. npm run babel
3. npm start
4. npm bs-start
5. navigate to http://localhost:3000/derek/templates/landing-page/video-LP
6. go edit styleguide/_themes/derek/scss/patterns/quote.scss , save
7. view your browser again .. should update
8. also go look at your terminal where you're running browsersync, you should see:
- - - - - - - 
To be discussed:
do we want to implement it this way with the snip added?
what files do we want to watch?
do we want browser sync to start when you start harp, or keep it a separate command?

RSWEB-8848: Add live reload

---

styleguide/_themes/derek/scss/patterns/cards/modules.scss

RSWEB-8793
Wanted all links in text and generals to have the link style, not just top level. Ran into the problem where links are nested in lists and they arent styling.

fix(global): link styles

---

styleguide/derek/global-components/ceiling/_ceiling.scss

Change summary:
* Set font size to a unified 1.15rem for ceiling
specifically, I put the vars in play, updated the `$navigation-font-size-medium` value so that it matches what the other nav items are. In line 86 I set that class to use the same var so that they're all unified. . . .

RSWEB-8999: [Bug] Ceiling link font size inconsistent

---

styleguide/_themes/global/scss/buttons.scss

RSWEB-9029
Change Summary:
* add text-decoration none to leaving class

RSWEB-9029: Text in hardcoded buttons have underlines on text

---

styleguide/derek/global-components/back-to-top/_back-to-top.scss
styleguide/derek/global-components/basement/_basement.scss
styleguide/derek/global-components/footer/footerLp.ejs
styleguide/derek/templates/landing-page/_layout.jade

Visible on:
http://localhost:3000/derek/templates/landing-page/cta-LP
Can ensure it doesnt cause styling issues on pages with the expanded footer here:
http://localhost:3000/derek/templates/service/service-overview
- Remove region selector for landing pages
- Add bottom border to back to top so there is a division on pages without the expanded footer

bug(derek): fix LP footer issues

---

styleguide/derek/view-templates/resource-center/_resource-center.scss
styleguide/derek/view-templates/resource-center/resource-center.ejs

This PR moves the featured resource graphic into the background instead of being explicitly added to behave like detailed resource graphic. This allows us to sit an image for an individual resource on top of the background.

RSWEB-9199: Featured resource graphic moved to background image

---

styleguide/derek/view-templates/resource-center/_resource-center.scss

Fix resource visited button state..
Before:
After:

fix(bug): resource button style after visit

---

styleguide/derek/global-components/filter-bar/filter-bar.js

This PR adds `parseInt()` back when using `$.css()`, as it's needed: 
e.g.
```
$('body').css('width');
"1196px"
```

fix(filter): bring back parseInt

---

styleguide/derek/pattern-components/resourceCenter-resource/_resourceCenter-resource.scss

RSWEB-9321
Adjusting the resource teaser link to sit at the bottom of the wrapper consistently.
Visible here:
http://localhost:3000/derek/view-templates/resource-center/resource-center

style(derek): Placing resource teaser links in consistent location

---

styleguide/derek/global-components/tracking/tracking.js
styleguide/derek/global-components/tracking/tracking.spec.js

Add tracking for internal clicks. Looking for the following functionality: 
If a user clicks on  "Solutions" >> "By Industry" >> "Healthcare" the following data will be captured and added to the datalayer. Healthcare:By Industry:Solutions

feat(tracking): Add tracking for internal nav.

---

styleguide/derek/pattern-components/service-level-teaser/_partials/teaser-link.ejs
styleguide/derek/pattern-components/service-level-teaser/_service-level-teaser.scss
styleguide/derek/pattern-components/service-level-teaser/service-level-teaser.ejs

See new pattern changes here:
service level teaser (3 up) shows link example,
the others are not linked
http://rsweb-9592-add-nonlink-slteasers.styleguide.dev.website.rackspace.com/derek/incubation/solutions

feat(slteaser): adding special case for non/linked cards

---

styleguide/derek/global-components/social/_social.scss
styleguide/derek/global-components/social/social.ejs

This PR fixes an issue with google plus button adding more width then necessary with inline styles dynamically in safari. 
Unfortunately, there is not class added to the dynamically created button. So I had to disable a couple of rules, only for the social.scss file.

RSWEB-9665: Fix google plus social button

---

.babelrc
package.json
styleguide/derek/global-components/hex/hex.js

Step 1 of many get the hex calculator code off cdn and into zoolander.
This is old code that will not run as it is with 'use strict'. I disabled this file from having that applied to it and had to create a work around to get it added to the code that is distributed.

feat(hex-calc): migrate hex calc into zoolander, original form

---

styleguide/_themes/global/scss/forms.scss
styleguide/derek/pattern-components/lp-callout/_lp-callout.scss
styleguide/derek/pattern-components/lp-callout/_partials/lp-callout-form.ejs

This PR moves some of the maintainable callout form css out into css inside of `.calloutForm`.  This is due to a weird drupalism, where we don't have full context of where a form lives and which build mode it uses without doing some weird hacks to core.

RSWEB-9528: Fix callout form

---

styleguide/derek/pattern-components/tabs/_tabs.scss

RSWEB-9343
Addition of the actual container mixin to the tab container class. Won't need any www work.
Both types of tabs can be seen here:
http://localhost:3000/derek/patterns/patterns
The tabs can also be seen as they would appear in the page here:
http://localhost:3000/derek/templates/content-driven/industry
Would still like to see a screen capture on staging to make sure there isn't something in Drupal that effects the containers. Or if any of the EBPs have been putting the tabs in container classes or rivers. If there is a mix then we may have a content issue we'll need to fix.

bug(derek): tab container full width

---

styleguide/derek/global-components/filter-bar/_filter-bar.scss

RSWEB-9999: Fix padding to better show chat slider

---

styleguide/derek/pattern-components/resourceCenter-resource/refresh/_resourceCenter-resource.scss

Bug fix for floating icon:
Page: https://www.rackspace.com/managed-aws/competencies
Issue:
http://rsweb-10004-fix-floating-icon.zoolander.dev.website.rackspace.com/managed-aws/competencies

fix(resource): fix floating icon with resource in panel

---

.sass-lint.yml
styleguide/_themes/derek/scss/components/pager.scss
styleguide/_themes/global/scss/swatch.scss
styleguide/derek/view-templates/events/events.ejs
styleguide/derek/view-templates/pagination.ejs
styleguide/derek/view-templates/resource-center/resource-center.ejs
styleguide/derek/view-templates/stories/stories.ejs

Since we're now using the default Drupal pagination markup, this PR adds in styling for it into Zoolander.
Events: http://rsweb-10124-pagerstyleclasses.styleguide.dev.website.rackspace.com/derek/view-templates/events/events
Stories: http://rsweb-10124-pagerstyleclasses.styleguide.dev.website.rackspace.com/derek/view-templates/stories/stories
Resources: http://rsweb-10124-pagerstyleclasses.styleguide.dev.website.rackspace.com/derek/view-templates/resource-center/resource-center

style(pagination): styling Drupal markup classes for pagination

---

styleguide/_layouts/default.jade
styleguide/global/global.js
styleguide/global/zoolander-only.js

This PR moves zoolander-only javascript out of the global.js file.  This is necessary for D8 based on how we're pulling in global.js

MTE-921: Move zoolander-only JS out of global.js

---

styleguide/derek/pattern-components/headers/headers.js

This PR resolves a banner redraw issue and resolves the `Uncaught TypeError: Cannot read property 'setAttributeNS' of null` error we're seeing on production right now.

MTE-2645: Prevent redraw and resolve JS issue

---

styleguide/derek/view-templates/events/_events.scss

This PR will line up the content margins for the event interior content to the rest of the page.

fix(margins): lining up margins on interior events page

---

styleguide/derek/pattern-components/about-river/_about-river.scss

https://jira.rax.io/browse/MTE-3870
Put in a change that applies to IE only.

MTE-3870: Home Page SVG Very Small on IE and FF (Windows)

---

styleguide/derek/global-components/mainnav/mainnav.js

This PR fixes the nav issues where the drop down triggers were not hiding submenu's when hovering off of them.

fix(nav): adding toggle for off hover on dropdown triggers

---

styleguide/derek/global-components/modal/_buy-now.scss

This PR fixes an issue with translations on the "Buy Now" buttons. 
Before:
After:

fix(buy-now): Resize button for translations

---

styleguide/derek/global-components/tracking/tracking.js
styleguide/derek/global-components/tracking/tracking.spec.js

This PR fixes an issue where cta tracking didn't work properly with alt tags.

MTE-4365: Use alt tags on track-cta click w/ images

---

styleguide/derek/global-components/modal/_modal.scss

This PR is for fixing mobile modal alignment issue (see right side of modal)
Before: 
After:

fix(modal): Fix mobile modal

---

styleguide/derek/global-components/modal/_buy-now.scss
styleguide/derek/pattern-components/page-banner/_page-banner.scss

This PR fixes a padding issue with German
Before:
- ![image](https://user-images.githubusercontent.com/5263371/57345678-540c8480-7111-11e9-8433-fd4e95e4bcf5.png)
- ![image](https://user-images.githubusercontent.com/5263371/57345674-51aa2a80-7111-11e9-950e-dffa8f0991c2.png)
After

fix(german): Fix icon padding for german

---

styleguide/derek/global-components/modal/_buy-now.scss
styleguide/derek/global-components/modal/buy-now.ejs

This PR has proposed buy now modal changes. 
I opted for the `display: none;` here to hide some of the cards, as it will work on deploy without changing HTML, which will buy us time between deploy and HTML modification on the Drupal end.

MTE-4573: Buy now changes

---

scripts/install-modules.sh

Trying to install zoolander 2.0.x as a dependency ie (```npm install git://github.com/rackerlabs/zoolander.git#2.0.x --save```) kept erroring on the zoolander postinstall script:
```bash
> ./scripts/install-modules.sh
cp: ./node_modules/mozilla-fira-pack/Fira: No such file or directory
```
This only happens when installing zoolander as a dependency and not inside the repo itself. After investigating it looked like a race condition where all of zoolanders dependencies were not available inside `node_modules` folder when the ```postinstall``` script ran.
Adding a check for the directory allowed the install to run successfully.

MTE 3807 Adding a fix for install bug

---

styleguide/global/global.js

Table plugin now checks if the mobile title is already there before it tries to add it.

fix(tables): fix for plugin adding multiple headers for mobile tables

---

styleguide/_themes/global/scss/fira-font-style.scss
styleguide/_themes/global/scss/fonts.scss
styleguide/derek/global-components/modal/_buy-now.scss
styleguide/derek/pattern-components/o365-table/_o365-table.scss
styleguide/derek/view-templates/events/_events.scss
styleguide/derek/view-templates/resource-center/_resource-center.scss

For research I removed all versions of Fira Sans and kept the most widely used one 'Fira-Sans-Light' and updated patterns using 500 font-weight to 600 to try and get the same effect. Other patterns trying to be bolder than that won't be able to.

research(fonts): removing some fira sans types in the name of research

---

styleguide/derek/global-components/social/_social.scss
styleguide/derek/global-components/social/social-tracking.js
styleguide/derek/global-components/social/social-tracking.spec.js
styleguide/derek/global-components/social/social.ejs
styleguide/derek/templates/thought-leadership-overview/article.ejs

JIRA: https://jira.rax.io/browse/MTE-5223
This PR resolves an issue with LinkedIn share buttons. See ticket for details, but essentially what was happening is at the point the `systemReady` event fired, the `IN-widget` class wasn't actually rendered yet. Looking through the [LinkedIn SDK docs](https://developer.linkedin.com/docs/js-sdk/api-reference/inauth_inevent_inui#content-par_longformtext_2), there does not appear to be an event that fires any later than `systemReady` so we can't rely on LinkedIn to know when that button is rendered. So what I've done instead is allowed for up to 300ms of time after `systemReady` for it to load, checking every 100ms. All of the tests I've done show it only needing one iteration through the interval, but I've allowed for 3 just in case. If it takes …

MTE-5223: Resolve linkedin tracking issue

---

styleguide/derek/templates/thought-leadership-overview/article.ejs
styleguide/derek/templates/thought-leadership-overview/solve-nav.js

This PR fixes a bug where the solve nav overlaid the banner content.  The DOM structure in zoolander is slightly different in Drupal vs Zoolander, so this is a less specific approach.
Also the article pages themselves should not have the "banner" region be a link.  That's just for the overview app. So I changed from `<a>` to `<div>` in zoolander here to match what's in Drupal.

MTE-5235: Fix overlay issue

---

styleguide/derek/templates/thought-leadership-overview/solve-nav.js

#731 didn't completely solve the problem. When used in combination with the solve app itself (which includes redraws), the element containing the class `.rsTl-feature-header` is redrawn, which means predefining a variable with it, doesn't work. Instead, we have to do a lookup each time. Also I bumped the timeout to a smaller window, to minimize time to redraw. Finally, I had to force a resize on init due to the way the SPA loads.

MTE-5235: Fixes overlap issue on solve app
